### ISSUE TITLE
mint = mintapi.Mint(user_name, password) just hangs on os X Sierra

### ISSUE THREAD

**Issue by lingxiao** [mintapi/mintapi#106]
I installed selenium and chrome driver, doing `driver = webdriver.Chrome()` works fine, furthermore doing `driver.get('https://www.mint.com/')` works as intended as well. However when I do

`mint = mintapi.Mint(user_name, password)`,  the program just hangs.

**Comment by mrooney** [comment]
Are there any errors in the console, or after it times out? If not, can you hit ctrl+c when it is running, can you paste the stracktrace?

**Comment by cmclaughlin** [comment]
^CTraceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/Users/username/virtualenvs/mintenv/lib/python2.7/site-packages/mintapi/api.py", line 69, in __init__
        self.login_and_get_token(email, password, ius_session, thx_guid)
      File "/Users/cmclaughlin/virtualenvs/mintenv/lib/python2.7/site-packages/mintapi/api.py", line 135, in login_and_get_token
        session_cookies = self.get_session_cookies(**data)
      File "/Users/username/virtualenvs/mintenv/lib/python2.7/site-packages/mintapi/api.py", line 195, in get_session_cookies
        time.sleep(1)
    KeyboardInterrupt

**Comment by itismouad** [comment]
I think this is due to Mint's security layer that forces you to send a code to your email address to verify your info.

**Comment by mrooney** [comment]
I'm going to close this out as I haven't heard of this issue recently, but please let me know if you can still reproduce it with the latest version.
