### ISSUE TITLE
chromedriver on arm32 (raspberry pi)

### ISSUE THREAD

**Issue by jorythompson** [mintapi/mintapi#167]
I had this working with a previous version (2.35) of chromedriver on my raspberry pi.  The version that mintapi (tries to) installs is 2.41.x.  The nifty new chromedriver(-finder?) does not include any ARM versions so you have to install one yourself.

I copied my 2.35 version over the one that mintapi installed but when my app runs, it fails with:
```
2019-02-18 02:38:41,114 - main -INFO - Getting logging configuration from:/mnt/usbdrive/python/MintCheck/logging.conf
2019-02-18 02:38:41,149 - MintConfigFile.__init__ -INFO - Starting session
2019-02-18 02:38:41,244 - MintCheck._get_data -INFO - getting transactions from 02/04/2019...
2019-02-18 02:39:14,401 - main -CRITICAL - Exception caught!
Traceback (most recent call last):
  File ".//mintCheck.py", line 185, in main
    mint_check.collect_and_send()
  File ".//mintCheck.py", line 149, in collect_and_send
    self._get_data(start_date - datetime.timedelta(days=max_day_error))
  File ".//mintCheck.py", line 50, in _get_data
    mint = self.connect()
  File ".//mintCheck.py", line 43, in connect
    headless=self.config.headless, mfa_method="sms")
  File "/mnt/usbdrive/python/github/mintapi/mintapi/api.py", line 219, in create
    return Mint(email, password, **opts)
  File "/mnt/usbdrive/python/github/mintapi/mintapi/api.py", line 215, in __init__
    session_path=session_path)
  File "/mnt/usbdrive/python/github/mintapi/mintapi/api.py", line 283, in login_and_get_token
    session_path=session_path)
  File "/mnt/usbdrive/python/github/mintapi/mintapi/api.py", line 113, in get_web_driver
    driver.find_element_by_id("ius-userid").send_keys(email)
  File "/home/jordan/.local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 360, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "/home/jordan/.local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/home/jordan/.local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/jordan/.local/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
NoSuchElementException: Message: no such element: Unable to locate element: {"method":"id","selector":"ius-userid"}
  (Session info: headless chrome=65.0.3325.181)
  (Driver info: chromedriver=2.35 (0),platform=Linux 4.14.79-v7+ armv7l)

2019-02-18 02:39:14,414 - main -CRITICAL - Traceback (most recent call last):

2019-02-18 02:39:14,416 - main -CRITICAL -   File ".//mintCheck.py", line 185, in main
    mint_check.collect_and_send()

2019-02-18 02:39:14,418 - main -CRITICAL -   File ".//mintCheck.py", line 149, in collect_and_send
    self._get_data(start_date - datetime.timedelta(days=max_day_error))

2019-02-18 02:39:14,419 - main -CRITICAL -   File ".//mintCheck.py", line 50, in _get_data
    mint = self.connect()

2019-02-18 02:39:14,421 - main -CRITICAL -   File ".//mintCheck.py", line 43, in connect
    headless=self.config.headless, mfa_method="sms")

2019-02-18 02:39:14,422 - main -CRITICAL -   File "/mnt/usbdrive/python/github/mintapi/mintapi/api.py", line 219, in create
    return Mint(email, password, **opts)

2019-02-18 02:39:14,424 - main -CRITICAL -   File "/mnt/usbdrive/python/github/mintapi/mintapi/api.py", line 215, in __init__
    session_path=session_path)

2019-02-18 02:39:14,425 - main -CRITICAL -   File "/mnt/usbdrive/python/github/mintapi/mintapi/api.py", line 283, in login_and_get_token
    session_path=session_path)

2019-02-18 02:39:14,427 - main -CRITICAL -   File "/mnt/usbdrive/python/github/mintapi/mintapi/api.py", line 113, in get_web_driver
    driver.find_element_by_id("ius-userid").send_keys(email)

2019-02-18 02:39:14,429 - main -CRITICAL -   File "/home/jordan/.local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 360, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)

2019-02-18 02:39:14,430 - main -CRITICAL -   File "/home/jordan/.local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']

2019-02-18 02:39:14,432 - main -CRITICAL -   File "/home/jordan/.local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)

2019-02-18 02:39:14,434 - main -CRITICAL -   File "/home/jordan/.local/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)

2019-02-18 02:39:14,435 - main -CRITICAL - NoSuchElementException: Message: no such element: Unable to locate element: {"method":"id","selector":"ius-userid"}
  (Session info: headless chrome=65.0.3325.181)
  (Driver info: chromedriver=2.35 (0),platform=Linux 4.14.79-v7+ armv7l)


2019-02-18 02:39:14,437 - main -CRITICAL - Last exception follows:
Traceback (most recent call last):
  File ".//mintCheck.py", line 185, in main
    mint_check.collect_and_send()
  File ".//mintCheck.py", line 149, in collect_and_send
    self._get_data(start_date - datetime.timedelta(days=max_day_error))
  File ".//mintCheck.py", line 50, in _get_data
    mint = self.connect()
  File ".//mintCheck.py", line 43, in connect
    headless=self.config.headless, mfa_method="sms")
  File "/mnt/usbdrive/python/github/mintapi/mintapi/api.py", line 219, in create
    return Mint(email, password, **opts)
  File "/mnt/usbdrive/python/github/mintapi/mintapi/api.py", line 215, in __init__
    session_path=session_path)
  File "/mnt/usbdrive/python/github/mintapi/mintapi/api.py", line 283, in login_and_get_token
    session_path=session_path)
  File "/mnt/usbdrive/python/github/mintapi/mintapi/api.py", line 113, in get_web_driver
    driver.find_element_by_id("ius-userid").send_keys(email)
  File "/home/jordan/.local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 360, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "/home/jordan/.local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/home/jordan/.local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/jordan/.local/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
NoSuchElementException: Message: no such element: Unable to locate element: {"method":"id","selector":"ius-userid"}
  (Session info: headless chrome=65.0.3325.181)
  (Driver info: chromedriver=2.35 (0),platform=Linux 4.14.79-v7+ armv7l)

2019-02-18 02:39:14,443 - main -CRITICAL - Traceback (most recent call last):

2019-02-18 02:39:14,445 - main -CRITICAL -   File ".//mintCheck.py", line 185, in main
    mint_check.collect_and_send()

2019-02-18 02:39:14,447 - main -CRITICAL -   File ".//mintCheck.py", line 149, in collect_and_send
    self._get_data(start_date - datetime.timedelta(days=max_day_error))

2019-02-18 02:39:14,449 - main -CRITICAL -   File ".//mintCheck.py", line 50, in _get_data
    mint = self.connect()

2019-02-18 02:39:14,451 - main -CRITICAL -   File ".//mintCheck.py", line 43, in connect
    headless=self.config.headless, mfa_method="sms")

2019-02-18 02:39:14,452 - main -CRITICAL -   File "/mnt/usbdrive/python/github/mintapi/mintapi/api.py", line 219, in create
    return Mint(email, password, **opts)

2019-02-18 02:39:14,454 - main -CRITICAL -   File "/mnt/usbdrive/python/github/mintapi/mintapi/api.py", line 215, in __init__
    session_path=session_path)

2019-02-18 02:39:14,455 - main -CRITICAL -   File "/mnt/usbdrive/python/github/mintapi/mintapi/api.py", line 283, in login_and_get_token
    session_path=session_path)

2019-02-18 02:39:14,457 - main -CRITICAL -   File "/mnt/usbdrive/python/github/mintapi/mintapi/api.py", line 113, in get_web_driver
    driver.find_element_by_id("ius-userid").send_keys(email)

2019-02-18 02:39:14,459 - main -CRITICAL -   File "/home/jordan/.local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 360, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)

2019-02-18 02:39:14,461 - main -CRITICAL -   File "/home/jordan/.local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']

2019-02-18 02:39:14,462 - main -CRITICAL -   File "/home/jordan/.local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)

2019-02-18 02:39:14,464 - main -CRITICAL -   File "/home/jordan/.local/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)

2019-02-18 02:39:14,466 - main -CRITICAL - NoSuchElementException: Message: no such element: Unable to locate element: {"method":"id","selector":"ius-userid"}
  (Session info: headless chrome=65.0.3325.181)
  (Driver info: chromedriver=2.35 (0),platform=Linux 4.14.79-v7+ armv7l)

```
I'm guessing that the problem is with the old version of the driver?  Is there any way to use older versions of the driver or compile your own?  I am also running on 32 bit (just to make things more interesting)

**Comment by mrooney** [comment]
Ah interesting. Are you wanting to use it without chromedriver but just trying to satisfy the dependency to get it to work, or would you prefer to use chromedriver? Happy to accept any Pull Requests that handle ARM!

**Comment by jorythompson** [comment]
No, I had been using mintapi with a previous version of chromedriver on the
ARM (Raspberry pi) for quite a while, but the new version of mintapi does
not work with my older version of chromedriver.
I'm trying build chromedriver on the pi, but it is not trivial. Is there
any way to downgrade mintapi,'s required version of chromedriver?

Thanks,
Jordan

**Comment by mrooney** [comment]
I believe that upgrade was to use a newer feature in later versions (perhaps the sessions?) so the simplest way would just be to downgrade mintapi itself if you don't need those newer features, until a newer chromedriver is available on your platform. Would that work in your case?

**Comment by jorythompson** [comment]
The thing I need most is the headless feature

**Comment by mushroomRetainer** [comment]
Any updates on this? I'm trying to get mintapi working on a raspberry pi as well, and running into similar issues with chromedriver version requirement. I've tried reverting back to earlier versions of mintapi, but I just get a jsondecodeerror instead.  It looks like the error with the current mintapi happens while trying to create a session. My goal is to just get the transaction info off mint.com, so I don't need all the bells and whistles if there is a past version of mintapi that will work.

**Comment by jorythompson** [comment]
Yes, I have it working again!!! I am upgraded and am running buster on my pi.  FWIW it is also running headless (no GUI or terminal)

**Comment by jorythompson** [comment]
Yes, I have it working again!!! I am upgraded and am running buster on my
pi.  FWIW it is also running headless (no GUI or terminal)

**Comment by mushroomRetainer** [comment]
That's great news. That gives me a good excuse to finally upgrade. Were you able to run the current version of mintapi? Which version of chromedriver did you use?

**Comment by jorythompson** [comment]
I am running the latest mintapi.  I Have chromedriver 78.0.3904.108 (I
honestly don't remember where I got it at this point

**Comment by mushroomRetainer** [comment]
Thanks! I was about to give up, so I'm happy to learn this is possible on a PI. I'll have to look around the internet to see what I can find; the version number helps a lot!

**Comment by mushroomRetainer** [comment]
Got it working! I'll leave my findings here in case they help whoever else stumbles on this issue (too real: https://xkcd.com/979/):
- my first issue was I was running an outdated version of Raspbian, so I couldn't install a recent enough version of chromedriver. Updating to Raspbian version 10 did the trick, and I was able to install version 78.0.39.108 of chromedriver and chromium-browser (which are the current ones available for Raspbian).
- my second issue was that chromedriver defaults to installing at /usr/bin/chromedriver, but mintapi looks for it in /home/pi/chromedriver. It appears mintapi installs chromedriver in this location if it can't find it there, but it installs a version that isn't compatible with the raspberry pi. So I had to remove that file and create a symbolic link between the two locations using "ln -s /usr/bin/chromedriver /home/pi/chromedriver"

Anyway, now it works flawlessly! Thanks again @jorythompson for the tips, and @mrooney for an awesome package!

**Comment by pisakhov** [comment]
It doesn't work for me for some reason:

- -I am using Raspberry Pi zero w
- -Python 3.7.3
- -ChromeDriver 78.0.3904.108 (4b26898a39ee037623a72fcfb77279fce0e7d648-refs/branch-heads/3904@{#889})
- -Chromium 78.0.3904.108 Built on Raspbian , running on Raspbian 10
- -mintapi 1.42

When I am using the code it gives me this issue:
`Traceback (most recent call last):
  File "mint.py", line 15, in <module>
    wait_for_sync_timeout=300,
  File "/usr/local/lib/python3.7/dist-packages/mintapi/api.py", line 373, in __init__
    wait_for_sync_timeout=wait_for_sync_timeout)
  File "/usr/local/lib/python3.7/dist-packages/mintapi/api.py", line 461, in login_and_get_token
    wait_for_sync_timeout=wait_for_sync_timeout)
  File "/usr/local/lib/python3.7/dist-packages/mintapi/api.py", line 216, in get_web_driver
    driver = Chrome(chrome_options=chrome_options, executable_path="%s" % executable_path)
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/chrome/webdriver.py", line 73, in __init__
    self.service.start()
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/common/service.py", line 76, in start
    stdin=PIPE)
  File "/usr/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: '/home/pi/chromedriver'
`

When I write chromedriver:
`Starting ChromeDriver 78.0.3904.108 (4b26898a39ee037623a72fcfb77279fce0e7d648-refs/branch-heads/3904@{#889}) on port 9515
Only local connections are allowed.
Please protect ports used by ChromeDriver and related test frameworks to prevent access by malicious code.
`

I want to execute into JSON file.
Thank you for helping.

**Comment by mushroomRetainer** [comment]
Did you try what I mentioned in my second bullet point? Check and see where you installed ChromeDriver because it might be in the wrong directory. Assuming the Pi zero has the same file structure, your ChromeDriver might have installed to `/usr/bin/chromedriver` by default, but mintapi is looking for it in `/home/pi/chromedriver,` and then mintapi is installing the wrong version when if can't find the one you installed. If that's the case, try creating a symbolic link between the two locations (after deleting the one mintapi installed if it's there):

- `ln -s /usr/bin/chromedriver /home/pi/chromedriver`

**Comment by pisakhov** [comment]
> Did you try what I mentioned in my second bullet point? Check and see where you installed ChromeDriver because it might be in the wrong directory. Assuming the Pi zero has the same file structure, your ChromeDriver might have installed to `/usr/bin/chromedriver` by default, but mintapi is looking for it in `/home/pi/chromedriver,` and then mintapi is installing the wrong version when if can't find the one you installed. If that's the case, try creating a symbolic link between the two locations (after deleting the one mintapi installed if it's there):
> 
> * `ln -s /usr/bin/chromedriver /home/pi/chromedriver`

You are my savor!
-It took over 15 minutes to process chromedriver on raspberry pi zero w. which one do you use?
-it means that I can make python script and place it only in /home/pi directory? 

Thank you so much!!!!

**Comment by mushroomRetainer** [comment]
I believe mine is a RP3 B (I don't have it handy). It takes maybe a minute or two to grab my transaction data (which is all I'm after). I have my python scripts in a subfolder, so I don't think you need to worry about the location of the scripts, just of the ChromeDriver. Glad you got it working!

**Comment by pisakhov** [comment]
> I believe mine is a RP3 B (I don't have it handy). It takes maybe a minute or two to grab my transaction data (which is all I'm after). I have my python scripts in a subfolder, so I don't think you need to worry about the location of the scripts, just of the ChromeDriver. Glad you got it working!

Thank you very much!
I might upgrade later to RP4. 
It works great and everything, but when I add a line to crontab it doesn't run.
Did you do something different than crontab?

**Comment by pisakhov** [comment]
ok, so, for now, I found an alternative way:

`sudo nano /home/pi/.bashrc`

the last line:
`echo Running at boot 
sudo sh /home/pi/run.sh`

run.sh file:

`#!/bin/bash

while true; do
   # do stuff
   python3 /home/pi/run.py &
   sleep 3600
done
`

when I do this way chromedriver works fine.
I write `ps aux`
and it shows that TTY is recognize, while crontab shows `?`
maybe that is the issue.. the TTY

**Comment by Porkbutts** [comment]
> * my second issue was that chromedriver defaults to installing at /usr/bin/chromedriver, but mintapi looks for it in /home/pi/chromedriver. It appears mintapi installs chromedriver in this location if it can't find it there, but it installs a version that isn't compatible with the raspberry pi. So I had to remove that file and create a symbolic link between the two locations using "ln -s /usr/bin/chromedriver /home/pi/chromedriver"
> 
> Anyway, now it works flawlessly! Thanks again @jorythompson for the tips, and @mrooney for an awesome package!

This got it working for me. Also had to run the tool with `--use-chromedriver-on-path` so it would stop trying to download it

**Comment by mrooney** [comment]
I created https://github.com/mintapi/mintapi/pull/282 to address this (and #281), please let me know if it looks good or what could be improved as I don't use Raspberry Pi and am just basing this off the instructions of others :)
