### ISSUE TITLE
Cannot set a frame with no defined index and a value that cannot be converted to a Series

### ISSUE THREAD

**Issue by jorythompson** [mintapi/mintapi#168]
Anyone else getting this error?
Here's the code:
```
       if self.config.debug_mint_download:
            logger.debug("Connecting to Mint...")
            mint = self.connect()
            logger.info("getting accounts...")
            self.accounts = mint.get_accounts(get_detail=False)
            count = 3
            while count > 0:
                logger.info("getting transactions from " + start_date.strftime('%m/%d/%Y') + "...")
                try:
                   # this is not working properly:
                    self.mint_transactions = mint.get_detailed_transactions(# include_investment=True,
                                                                            # skip_duplicates=self.config.mint_remove_duplicates,
                                                                            start_date=start_date.strftime('%m/%d/%y'))
                    count = 0
                except Exception as e:
                    print e
                    count -= 1
                    if count == 0:
                        raise e
 ```
Here's the exception:
```
2019-03-02 01:55:33,668 - mintCheck.main -CRITICAL - Exception caught!
  File "/Users/jrt/Documents/projects/MintCheck/mintCheck.py", line 178, in main
    mint_check.collect_and_send()
  File "/Users/jrt/Documents/projects/MintCheck/mintCheck.py", line 133, in collect_and_send
    self._get_data(start_date - datetime.timedelta(days=max_day_error))
  File "/Users/jrt/Documents/projects/MintCheck/mintCheck.py", line 63, in _get_data
    raise e
ValueError: Cannot set a frame with no defined index and a value that cannot be converted to a Series
2019-03-02 01:55:33,669 - mintCheck.main -CRITICAL - Traceback (most recent call last):

2019-03-02 01:55:33,669 - mintCheck.main -CRITICAL -   File "/Users/jrt/Documents/projects/MintCheck/mintCheck.py", line 178, in main
    mint_check.collect_and_send()

2019-03-02 01:55:33,670 - mintCheck.main -CRITICAL -   File "/Users/jrt/Documents/projects/MintCheck/mintCheck.py", line 133, in collect_and_send
    self._get_data(start_date - datetime.timedelta(days=max_day_error))

2019-03-02 01:55:33,670 - mintCheck.main -CRITICAL -   File "/Users/jrt/Documents/projects/MintCheck/mintCheck.py", line 63, in _get_data
    raise e

2019-03-02 01:55:33,671 - mintCheck.main -CRITICAL - ValueError: Cannot set a frame with no defined index and a value that cannot be converted to a Series

2019-03-02 01:55:33,671 - mintCheck.main -CRITICAL - Last exception follows:
2019-03-02 01:55:33,672 - mintCheck.main -CRITICAL - Traceback (most recent call last):

2019-03-02 01:55:33,672 - mintCheck.main -CRITICAL -   File "/Users/jrt/Documents/projects/MintCheck/mintCheck.py", line 178, in main
    mint_check.collect_and_send()

2019-03-02 01:55:33,672 - mintCheck.main -CRITICAL -   File "/Users/jrt/Documents/projects/MintCheck/mintCheck.py", line 133, in collect_and_send
    self._get_data(start_date - datetime.timedelta(days=max_day_error))

2019-03-02 01:55:33,673 - mintCheck.main -CRITICAL -   File "/Users/jrt/Documents/projects/MintCheck/mintCheck.py", line 63, in _get_data
    raise e

2019-03-02 01:55:33,673 - mintCheck.main -CRITICAL - ValueError: Cannot set a frame with no defined index and a value that cannot be converted to a Series
```
Traceback (most recent call last):
  File "/Users/jrt/Documents/projects/MintCheck/mintCheck.py", line 178, in main
    mint_check.collect_and_send()
  File "/Users/jrt/Documents/projects/MintCheck/mintCheck.py", line 133, in collect_and_send
    self._get_data(start_date - datetime.timedelta(days=max_day_error))
  File "/Users/jrt/Documents/projects/MintCheck/mintCheck.py", line 63, in _get_data
    raise e
ValueError: Cannot set a frame with no defined index and a value that cannot be converted to a Series`

**Comment by jaron-l** [comment]
You're stack trace never actually references mintapi nor the line that you mention where the problem is at. Are you sure that it's a problem with mintapi and not with another part of your code?
