### ISSUE TITLE
headless=False method working, but headless=True not working

### ISSUE THREAD

**Issue by ktop77** [mintapi/mintapi#216]
Recently been having the issue where I am fully able to login to my mint account through the browser method of the api (headless=False), but am having an issue using the headless mode (headless=True).

When using the headless method, I am always prompted with entering the 6 digit MFA code (which I do successfully get sent to my phone), but then when I enter the code to the python input prompt, I get this string of errors:
```
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/mintapi/api.py", line 265, in get_web_driver
    mfa_method_option.click()
  File "/home/pi/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/home/pi/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "/home/pi/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/pi/.local/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotInteractableException: Message: element not interactable
  (Session info: headless chrome=78.0.3904.108)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/Documents/Python_Projects/10_Projects/Mint/download_mint_data.py", line 20, in <module>
    mint = mintapi.Mint('ktopolewski7@gmail.com',os.environ.get('MINT_PASS'), headless=True, mfa_method='sms')
  File "/home/pi/.local/lib/python3.7/site-packages/mintapi/api.py", line 373, in __init__
    wait_for_sync_timeout=wait_for_sync_timeout)
  File "/home/pi/.local/lib/python3.7/site-packages/mintapi/api.py", line 461, in login_and_get_token
    wait_for_sync_timeout=wait_for_sync_timeout)
  File "/home/pi/.local/lib/python3.7/site-packages/mintapi/api.py", line 280, in get_web_driver
    warnings.warn("Giving up on handling MFA. Please complete "
UserWarning: Giving up on handling MFA. Please complete the MFA process manually in the browser.

```

I have tried completing the MFA process through the browser as recommended, but I still always get prompted and sent a 6 digit code when I do the headless method (but not for the browser method).

**Comment by jaron-l** [comment]
This is the exact same error as on #232 so it could be related. #232 doesn't relate to using headless or not but it could be coincidence as both sign in workflows are still possible.

Have you stress tested running headless to find an error rate?

Also, you could just pull #234 to try to see if it fixes your problem.
