### ISSUE TITLE
Fetching credit information results in: "invalid cookie domain: Cookie 'domain' mismatch"

### ISSUE THREAD

**Issue by ScottG489** [mintapi/mintapi#313]
**Describe the bug**
Trying to retrieve my `--credit-score` results in this error: `Message: invalid cookie domain: Cookie 'domain' mismatch`

`--credit-report` also causes this error. I've tried a few other flags such as `--net-worth`, `--budgets`, and `--transactions` and those works fine.

**What version of MintAPI are you using?**
I'm running off source on `master`, currently `5bb5dd5a8ad4c3bce98dfaabfc124c560ec8ae84`.

**What command[s] did you run / steps to reproduce?**
`python3 ./mintapi/api.py --no_wait_for_sync --mfa-method soft-token --mfa-token "XXXXX" "XXXXX" "XXXXX" --credit-score`

**Stacktrace/error received:**
```
Traceback (most recent call last):
  File "/home/scott/code/mintapi/./mintapi/api.py", line 1412, in <module>
    main()
  File "/home/scott/code/mintapi/./mintapi/api.py", line 1377, in main
    data = mint.get_credit_score()
  File "/home/scott/code/mintapi/./mintapi/api.py", line 1091, in get_credit_score
    report = self.get_credit_report(limit=1, details=False)
  File "/home/scott/code/mintapi/./mintapi/api.py", line 1107, in get_credit_report
    response = self.get(
  File "/home/scott/code/mintapi/./mintapi/api.py", line 613, in get
    return self.driver.request('GET', url, **kwargs)
  File "/home/scott/.local/lib/python3.9/site-packages/seleniumrequests/request.py", line 232, in request
    self.add_cookie(cookie_dict)
  File "/home/scott/.local/lib/python3.9/site-packages/seleniumrequests/request.py", line 154, in add_cookie
    super(RequestsSessionMixin, self).add_cookie(cookie_dict)
  File "/home/scott/.local/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 894, in add_cookie
    self.execute(Command.ADD_COOKIE, {'cookie': cookie_dict})
  File "/home/scott/.local/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/scott/.local/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidCookieDomainException: Message: invalid cookie domain: Cookie 'domain' mismatch
  (Session info: chrome=94.0.4606.54)
```

**What did you expect to happen?**
I expected my credit score to be returned.

**What actually happened?**
I got the above stacktrace right after login completes.

**Additional context**
This is just a hunch, but the error says there's a "domain mismatch", so perhaps it has something to do with the fact that the credit information is fetched from a different domain (https://credit.finance.intuit.com).

**Comment by ScottG489** [comment]
Seems like now I'm getting this error even when specifying `--net-worth`.
