### ISSUE TITLE
Credit Report requests are failing

### ISSUE THREAD

**Issue by burkematthew** [mintapi/mintapi#349]
**Describe the bug**
I am unable to process 

What version of MintAPI are you using?

* I tested on the current version of main
* I also tested on a branch created from commit `4c0a1713dc7aa0f9691b9989d6db3834fe613490` (https://github.com/mintapi/mintapi/commit/4c0a1713dc7aa0f9691b9989d6db3834fe613490)
* I also tested on a branch created from commit `56c01912309dad557bd70125645ef8af994c0382` (https://github.com/mintapi/mintapi/commit/56c01912309dad557bd70125645ef8af994c0382)

What command[s] did you run / steps to reproduce?

`python3 mintapi/api.py --keyring burkematthewjoseph@gmail.com --credit-report -f ./credit.json --session-path=No`

Stacktrace/error received:

`Traceback (most recent call last):
  File "/Users/matthewburke/github/mintapi/mintapi/api.py", line 1451, in <module>
    main()
  File "/Users/matthewburke/github/mintapi/mintapi/api.py", line 1418, in main
    data = mint.get_credit_report(details=True)
  File "/Users/matthewburke/github/mintapi/mintapi/api.py", line 1148, in get_credit_report
    credit_report['reports'] = response.json()
  File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 910, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`

**What did you expect to happen?**

The request was complete and save data related to credit reports.

**What actually happened?**

The request failed due to missing data from the response.

**Additional context**
This seems to be a change on the Mint side because with `56c01912309dad557bd70125645ef8af994c0382` , I was able to get results.

**Comment by jaron-l** [comment]
The JSON code means that nothing was returned in your stack trace, not even an error. It's likely that you had connection problems and never hit mint.com. This problem would seem intermittent because it worked on 56c019 but not more recent ones which shouldn't have affected your command if I understand it correctly.

**Comment by burkematthew** [comment]
@jaron-l it's isolated to this specific type of request. All others work. I've also tried several different days with the same behavior.

**Comment by jaron-l** [comment]
Got it. That does sound weird. I'll take a look.

**Comment by jaron-l** [comment]
I can't get it to fail on any commit since `56c0191`. I'm just calling `get_credit_report` and asserting all the keys are there. Seems that should trigger what you're seeing. Can you confirm your sign in process worked successfully?

**Comment by burkematthew** [comment]
@jaron-l it's not that the tests are failing, it's that the response itself from the endpoint fails.  If you use the same set of commands I did at the command-line, do you get a successful response with the data?

**Comment by jaron-l** [comment]
I wrote my own small test that calls `get_credit_report` and asserts that the response contains all the needed keys. It is working on the endpoint mentioned. I can try the command line route but it shouldn't make a difference unless it's the way the command line sets up the Mint class.

**Comment by burkematthew** [comment]
Oh I see. I misunderstood. This is super weird. I guess I'll try again and see if I'm having the issue today.

**Comment by burkematthew** [comment]
@jaron-l Okay I figured out the key distinction.  In `headless` mode, the request works correctly.  I think it must be because of the cookie handling with regards to the separate URL (`MINT_CREDIT_URL`).  With that being said, we should either add a validation for `--credit-report` or `--credit-score` that requires the use of `--headless` or we need to hardcode the use of `--headless` with either of these scenarios.  I'm inclined to say the former.

@mrooney I'm curious your thoughts on the above as well.

**Comment by jaron-l** [comment]
I would think we should investigate whether there is a way to make it work in GUI mode before we rule it out.

**Comment by jaron-l** [comment]
I was able to reproduce this today. I think the best way to handle this might be to do it the same way that seleniumrequests merges the cookies from different domains. We probably need to be using seleniumrequests to manage the cookies for the credit endpoint anyways because that is the whole reason that we use it in the first place. I'll continue to look into this. Hopefully there's a way to manage the two different domains.

**Comment by burkematthew** [comment]
@jaron-l let me know if you want me to look into anything with it as well.
