### ISSUE TITLE
docker container fails with `--extended-transactions`

### ISSUE THREAD

**Issue by timdau** [mintapi/mintapi#404]
**Describe the bug**
When running mintapi from the provided docker image with --extended-transactions it fails.

What version of MintAPI are you using?
ghcr.io/mintapi/mintapi                                 latest           0e29c480113c   3 weeks ago      1.56GB

What command[s] did you run / steps to reproduce?
Stacktrace/error received:
`docker run --rm --shm-size=2g ghcr.io/mintapi/mintapi mintapi $username $password --headless --use-chromedriver-on-path --extended-transactions
Traceback (most recent call last):
  File "/home/seluser/.local/bin/mintapi", line 8, in <module>
    sys.exit(main())
  File "/home/seluser/.local/lib/python3.8/site-packages/mintapi/cli.py", line 507, in main
    data = mint.get_detailed_transactions(
  File "/home/seluser/.local/lib/python3.8/site-packages/mintapi/api.py", line 472, in get_detailed_transactions
    result = self.get_transactions_json(
  File "/home/seluser/.local/lib/python3.8/site-packages/mintapi/api.py", line 429, in get_transactions_json
    if __include_investments_with_transactions(id, include_investment):
NameError: name '_Mint__include_investments_with_transactions' is not defined`

**What did you expect to happen?**
Expected extended transactions output... a bunch of json.

**What actually happened?**
Application errored out.

**Additional context**
N/A

**Comment by timdau** [comment]
If it helps, regular -t doesn't work either.  With or without the start date.

**Comment by timdau** [comment]
Using the latest docker image and upgrading selenium changes the behaviour:

`+ /home/seluser/.local/bin/mintapi $username $password --use-chromedriver-on-path --headless --extended-transactions --start-date 03/05/22
Traceback (most recent call last):
  File "/home/seluser/.local/bin/mintapi", line 8, in <module>
    sys.exit(main())
  File "/home/seluser/.local/lib/python3.8/site-packages/mintapi/cli.py", line 507, in main
    data = mint.get_detailed_transactions(
  File "/home/seluser/.local/lib/python3.8/site-packages/mintapi/api.py", line 483, in get_detailed_transactions
    df.amount = df.apply(reverse_credit_amount, axis=1)
  File "/home/seluser/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 5612, in __setattr__
    self[name] = value
  File "/home/seluser/.local/lib/python3.8/site-packages/pandas/core/frame.py", line 3645, in __setitem__
    self._set_item_frame_value(key, value)
  File "/home/seluser/.local/lib/python3.8/site-packages/pandas/core/frame.py", line 3775, in _set_item_frame_value
    raise ValueError("Columns must be same length as key")
ValueError: Columns must be same length as key`

But it works without specifying the start date.  Seems like there is a problem with comparing the start date.  Weird that this doesn't happen on my non-docker system.

**Comment by timdau** [comment]
I guess this should be closed because --extended-transactions is no longer supported.

**Comment by mrooney** [comment]
Thanks! Let me know if https://github.com/mintapi/mintapi/pull/477 addresses any docs concerns.
