### ISSUE TITLE
no such element: Unable to locate element: {"method":"css selector","selector":"[id="ius-userid"]"}

### ISSUE THREAD

**Issue by dzg** [mintapi/mintapi#406]
As of yesterday ...

**What version of MintAPI are you using?**
1.63

**What command[s] did you run / steps to reproduce?**
```
mint = mintapi.Mint(userid, pw,
	headless=True,
	wait_for_sync=True,
	mfa_method='soft-token',
	mfa_token=token,
)
```

**Stacktrace/error received:**
```
Message: no such element: Unable to locate element: {"method":"css selector","selector":"[id="ius-userid"]"}
  (Session info: headless chrome=99.0.4844.51)
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/mintapi/api.py", line 235, in login_and_get_token
    self.status_message, self.token = sign_in(
  File "/usr/local/lib/python3.9/site-packages/mintapi/signIn.py", line 313, in sign_in
    handle_same_page_username_password(driver, email, password)
  File "/usr/local/lib/python3.9/site-packages/mintapi/signIn.py", line 360, in handle_same_page_username_password
    email_input = driver.find_element_by_id("ius-userid")
  File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 360, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[id="ius-userid"]"}
  (Session info: headless chrome=99.0.4844.51)
```

**Comment by burkematthew** [comment]
Hi @dzg ! It looks like this is a duplicate issue. Please see #405 for updates to this issue. To

**Comment by Deepak-01** [comment]
@burkematthew - I see that this issue was marked as resolved. However, it appears that I'm still having trouble with it. Do I need to uninstall and reinstall mintapi through the terminal for the changes to take effect?

```
Message: no such element: Unable to locate element: {"method":"css selector","selector":"[id="ius-userid"]"}
  (Session info: chrome=99.0.4844.51)
Traceback (most recent call last):
  File "/Users/deepak.krishnan/Library/Python/3.8/lib/python/site-packages/mintapi/api.py", line 235, in login_and_get_token
    self.status_message, self.token = sign_in(
  File "/Users/deepak.krishnan/Library/Python/3.8/lib/python/site-packages/mintapi/signIn.py", line 313, in sign_in
    handle_same_page_username_password(driver, email, password)
  File "/Users/deepak.krishnan/Library/Python/3.8/lib/python/site-packages/mintapi/signIn.py", line 360, in handle_same_page_username_password
    email_input = driver.find_element_by_id("ius-userid")
  File "/Users/deepak.krishnan/Library/Python/3.8/lib/python/site-packages/selenium/webdriver/remote/webdriver.py", line 360, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "/Users/deepak.krishnan/Library/Python/3.8/lib/python/site-packages/selenium/webdriver/remote/webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "/Users/deepak.krishnan/Library/Python/3.8/lib/python/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/deepak.krishnan/Library/Python/3.8/lib/python/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[id="ius-userid"]"}
  (Session info: chrome=99.0.4844.51)

```

**Comment by mrooney** [comment]
Hi @Deepak-01 ! You need to upgrade to mintapi 1.64 however you installed it. Probably `pip install --upgrade mintapi`

**Comment by Deepak-01** [comment]
That fixed it. Thanks a lot!
