### ISSUE TITLE
Maxretry issue

### ISSUE THREAD

**Issue by Deepak-01** [mintapi/mintapi#407]
Hey folks, I've been running into this issue for the past 2 days when attempting to get transactions. Does any one know if there's something I'm missing here? I am using a new laptop and I did install all the necessary libraries for this to work. I'm not a developer. I'm merely using this to make my life a little easier, so, I do beg pardon for any glaring mistakes I may have made. 

`MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=53555): Max retries exceeded with url: /session/173fc5d851d97ad363e2d1498ae28f39/window/handles (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x121311100>: Failed to establish a new connection: [Errno 61] Connection refused'))`

I'm running Google chrome Version 99.0.4844.51 which is the latest. 

here's the extended traceback:
Message: no such element: Unable to locate element: {"method":"css selector","selector":"[id="ius-userid"]"}
  (Session info: chrome=99.0.4844.51)
Traceback (most recent call last):
  File "/Users/deepak.krishnan/Library/Python/3.8/lib/python/site-packages/mintapi/api.py", line 235, in login_and_get_token
    self.status_message, self.token = sign_in(
  File "/Users/deepak.krishnan/Library/Python/3.8/lib/python/site-packages/mintapi/signIn.py", line 313, in sign_in
    handle_same_page_username_password(driver, email, password)
  File "/Users/deepak.krishnan/Library/Python/3.8/lib/python/site-packages/mintapi/signIn.py", line 360, in handle_same_page_username_password
    email_input = driver.find_element_by_id("ius-userid")
  File "/Users/deepak.krishnan/Library/Python/3.8/lib/python/site-packages/selenium/webdriver/remote/webdriver.py", line 360, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "/Users/deepak.krishnan/Library/Python/3.8/lib/python/site-packages/selenium/webdriver/remote/webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "/Users/deepak.krishnan/Library/Python/3.8/lib/python/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/deepak.krishnan/Library/Python/3.8/lib/python/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[id="ius-userid"]"}
  (Session info: chrome=99.0.4844.51)

**Comment by burkematthew** [comment]
Hi @Deepak-01 ! Thanks for the report. I believe the root issue here is related to the inability to find the element, similar to issue #405 . The max retry issue is a side effect of the failure in the other flow. We'll use the referenced issue as the primary tracker for this problem. If you still experience this issue after the fix, we'll reopen.
