### ISSUE TITLE
ImportError: cannot import name 'ChromiumEdge' from 'selenium.webdriver'

### ISSUE THREAD

**Issue by timdau** [mintapi/mintapi#412]
**Describe the bug**
When running mintapi it errors out with `ImportError: cannot import name 'ChromiumEdge' from 'selenium.webdriver'`

What version of MintAPI are you using?
1.64
What command[s] did you run / steps to reproduce?
mintapi -h
Stacktrace/error received:
`# mintapi -h
/usr/lib/python3/dist-packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.26.7) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)
Traceback (most recent call last):
  File "/usr/local/bin/mintapi", line 6, in <module>
    from mintapi.cli import main
  File "/usr/local/lib/python3.7/dist-packages/mintapi/__init__.py", line 3, in <module>
    from mintapi.api import *
  File "/usr/local/lib/python3.7/dist-packages/mintapi/api.py", line 15, in <module>
    from mintapi.signIn import sign_in, _create_web_driver_at_mint_com
  File "/usr/local/lib/python3.7/dist-packages/mintapi/signIn.py", line 28, in <module>
    from seleniumrequests import Chrome
  File "/usr/local/lib/python3.7/dist-packages/seleniumrequests/__init__.py", line 4, in <module>
    from selenium.webdriver import ChromiumEdge as _ChromiumEdge
ImportError: cannot import name 'ChromiumEdge' from 'selenium.webdriver' (/usr/local/lib/python3.7/dist-packages/selenium/webdriver/__init__.py)`
**What did you expect to happen?**
The help message output

**What actually happened?**
Stack trace.

**Additional context**
If it helps, the docker container is giving the same error.  The error happens regardless of options specified.

**Comment by timdau** [comment]
Work around: upgrade selenium
You get the following error, but it starts working again.

`ERROR: mintapi 1.64 has requirement selenium<4.0.0, but you'll have selenium 4.1.2 which is incompatible.`

Confirmed this works in the docker image but it still has the error in #404.
