### ISSUE TITLE
Message: unknown error: session deleted because of page crash

### ISSUE THREAD

**Issue by sooth** [mintapi/mintapi#417]
**Describe the bug**
Login fails

**What version of MintAPI are you using?**
root@dev2:~/mintapi# pip3 list | grep mintapi
mintapi                1.64      

**What command[s] did you run / steps to reproduce?**
root@dev2:~/mintapi# python3 mintapi --transactions --filename transactions.csv --headless username password

**Stacktrace/error received:**
`Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=99.0.4844.51)
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/mintapi-1.64-py3.8.egg/mintapi/api.py", line 235, in login_and_get_token
    self.status_message, self.token = sign_in(
  File "/usr/local/lib/python3.8/dist-packages/mintapi-1.64-py3.8.egg/mintapi/signIn.py", line 339, in sign_in
    password_page(driver, password)
  File "/usr/local/lib/python3.8/dist-packages/mintapi-1.64-py3.8.egg/mintapi/signIn.py", line 525, in password_page
    driver.find_element_by_id(
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/webdriver.py", line 360, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=99.0.4844.51)

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/urllib3-1.26.8-py3.8.egg/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/usr/local/lib/python3.8/dist-packages/urllib3-1.26.8-py3.8.egg/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/usr/local/lib/python3.8/dist-packages/urllib3-1.26.8-py3.8.egg/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused`

**What did you expect to happen?**
Transactions to be dumped

**What actually happened?**
The above error

**Additional context**

**Comment by burkematthew** [comment]
@sooth your original title is consistent with an issue that we're aware of and working on. Is that still what's going on for you?

**Comment by sooth** [comment]
I get a different error message depending on how I call the program, but yes I can reliably reproduce the original error message as well.

**Comment by burkematthew** [comment]
@sooth I'm going to close this one out then and track progress of the fix on #418 .  If you continue to have issues after we identify the fix for that issue, we can reopen this.  However, I do anticipate it's the same issue.
