### ISSUE TITLE
Login hangs after 2FA code entered

### ISSUE THREAD

**Issue by champbronc2** [mintapi/mintapi#426]
Regardless of headless or not, after logging in successfully, the CLI will hang. 

What version of MintAPI are you using?
Latest version of main ([7066588](https://github.com/mintapi/mintapi/commit/7066588ab1b305948b093b196ac4650237c28599))

What command[s] did you run / steps to reproduce?
CLI

Stacktrace/error received:

```
mintapi --keyring x@x.com
Please enter your 6-digit MFA code: 454306
^CTraceback (most recent call last):
  File "/usr/local/bin/mintapi", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/mintapi/cli.py", line 439, in main
    mint = Mint(
  File "/usr/local/lib/python3.9/site-packages/mintapi/api.py", line 121, in __init__
    self.login_and_get_token(
  File "/usr/local/lib/python3.9/site-packages/mintapi/api.py", line 235, in login_and_get_token
    self.status_message, self.token = sign_in(
  File "/usr/local/lib/python3.9/site-packages/mintapi/signIn.py", line 327, in sign_in
    bypass_verified_user_page(driver)
  File "/usr/local/lib/python3.9/site-packages/mintapi/signIn.py", line 400, in bypass_verified_user_page
    skip_for_now = driver.find_element_by_id("ius-verified-user-update-btn-skip")
  File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 360, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 319, in execute
    response = self.command_executor.execute(driver_command, params)
  File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/remote/remote_connection.py", line 374, in execute
    return self._request(command_info[0], url, body=data)
  File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/remote/remote_connection.py", line 397, in _request
    resp = self._conn.request(method, url, body=body, headers=headers)
  File "/usr/local/lib/python3.9/site-packages/urllib3/request.py", line 78, in request
    return self.request_encode_body(
  File "/usr/local/lib/python3.9/site-packages/urllib3/request.py", line 170, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "/usr/local/lib/python3.9/site-packages/urllib3/poolmanager.py", line 376, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1377, in getresponse
    response.begin()
  File "/usr/local/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 320, in begin
    version, status, reason = self._read_status()
  File "/usr/local/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 281, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
KeyboardInterrupt
```

Using macOS

**Comment by mrooney** [comment]
Can you please include the commit or version number? "Latest version of main" is not super helpful as new commits come in :)

**Comment by champbronc2** [comment]
Thanks for the reply @mrooney , commit [7066588](https://github.com/mintapi/mintapi/commit/7066588ab1b305948b093b196ac4650237c28599)

**Comment by MikeVezina** [comment]
@champbronc2 not sure, but this may be related to the issue that I just created: #428, which also hangs after MFA.

When running with the browser (headless=False), does it get stuck on the same screen as shown in the issue above?

**Comment by burkematthew** [comment]
@champbronc2 can you pull the latest from main and see if this fixes your issue?

**Comment by sooth** [comment]
With version 1.66 I still experience this

**Comment by burkematthew** [comment]
@sooth can you outline here what you see in non-headless mode. That will give us context as to where your flow is hanging.

**Comment by sooth** [comment]
I no longer hang, I crash when running from main. Here's my login flow:
<img width="792" alt="mint1" src="https://user-images.githubusercontent.com/1765148/166157042-e6b30596-9c17-4faa-8b1d-d9fad4bfdd38.png">
<img width="792" alt="mint2" src="https://user-images.githubusercontent.com/1765148/166157045-45d45da2-4f73-4055-a329-dce31b05e9cd.png">
<img width="792" alt="mint3" src="https://user-images.githubusercontent.com/1765148/166157047-86aa0e0e-d0c9-4793-8679-e02f1f290651.png">
<img width="792" alt="mint4" src="https://user-images.githubusercontent.com/1765148/166157049-1704b41a-2084-4e1a-a37e-a205c2a8d4ec.png">
<img width="792" alt="mint5" src="https://user-images.githubusercontent.com/1765148/166157053-729f3193-3b9f-491a-9d30-0bbd36835481.png">

**Comment by burkematthew** [comment]
@sooth the robot screen is probably what's causing the hanging issue. Also, the verification selection screen has an issue on main that an open PR fixes.

**Comment by sooth** [comment]
I don't get it, I'm asked for robot and 2fa each and every time. I have session path set but it always asks. So frustrating, never had this before.

**Comment by burkematthew** [comment]
@sooth there is another issue out there about session path not saving the MFA. 

And I think the new UI has included some stronger bot detection based on what I've seen in some other reports.

**Comment by burkematthew** [comment]
Note to self: add a wait in account_selection_page.
