### ISSUE TITLE
list index out of range for mfa_result

### ISSUE THREAD

**Issue by luigi311** [mintapi/mintapi#453]
**Describe the bug**
When on the mfa page it will error out after a few seconds with the following error
```
Python\Python310\site-packages\mintapi\signIn.py", line 541, in set_mfa_method
    mfa_result = list(mfa)[0]
IndexError: list index out of range
```

What version of MintAPI are you using? 
2ae42d00560dfdad5780866b53a099503fe861ad
What command[s] did you run / steps to reproduce?
Install mintapi via
```
pip install git+https://github.com/mintapi/mintapi.git@2ae42d00560dfdad5780866b53a099503fe861ad
```
run the mintapi with the following configuration
```
mint = mintapi.Mint(
        "{EMAIL_ADDRESS}",  # Email used to log in to Mint
        "{PASSWORD}",  # Your password used to log in to mint
        # Optional parameters
        mfa_method="soft-token",  # See MFA Methods section
        # Can be 'sms' (default), 'email', or 'soft-token'.
        # if mintapi detects an MFA request, it will trigger the requested method
        # and prompt on the command line.
        mfa_input_callback=None,  # see MFA Methods section
        # can be used with any mfa_method
        # A callback accepting a single argument (the prompt)
        # which returns the user-inputted 2FA code. By default
        # the default Python `input` function is used.
        mfa_token="{MFA_TOKEN}",  # see MFA Methods section
        # used with mfa_method='soft-token'
        # the token that is used to generate the totp
        intuit_account=None,  # account name when multiple accounts are registered with this email.
        headless=False,  # Whether the chromedriver should work without opening a
        # visible window (useful for server-side deployments)
        # None will use the default account.
        session_path=None,  # Directory that the Chrome persistent session will be written/read from.
        # To avoid the 2FA code being asked for multiple times, you can either set
        # this parameter or log in by hand in Chrome under the same user this runs
        # as.
        imap_account=None,  # account name used to log in to your IMAP server
        imap_password=None,  # account password used to log in to your IMAP server
        imap_server=None,  # IMAP server host name
        imap_folder="INBOX",  # IMAP folder that receives MFA email
        wait_for_sync=False,  # do not wait for accounts to sync
        wait_for_sync_timeout=300,  # number of seconds to wait for sync
        use_chromedriver_on_path=False,  # True will use a system provided chromedriver binary that
        # is on the PATH (instead of downloading the latest version)
    )
```
Since headless is False it will open the chrome window and proceed to v2 of the UI for me and get to the captcha which i have to manually do, afterwards it will go to the password page and fill that in automatically and then get to the MFA page which is where it fails
Stacktrace/error received:
```
Traceback (most recent call last):
  File "C:\Users\{USER}\AppData\Roaming\Python\Python310\site-packages\mintapi\api.py", line 178, in login_and_get_token
    self.status_message = sign_in(
  File "C:\Users\{USER}\AppData\Roaming\Python\Python310\site-packages\mintapi\signIn.py", line 359, in sign_in
    mfa_page(
  File "C:\Users\{USER}\AppData\Roaming\Python\Python310\site-packages\mintapi\signIn.py", line 485, in mfa_page
    mfa_result = set_mfa_method(driver, mfa_method)
  File "C:\Users\{USER}\AppData\Roaming\Python\Python310\site-packages\mintapi\signIn.py", line 541, in set_mfa_method
    mfa_result = list(mfa)[0]
IndexError: list index out of range
```
**What did you expect to happen?**
I expected it to input the mfa token and login successfully
**What actually happened?**
It failed to generate the mfa token and login
**Additional context**

**Comment by burkematthew** [comment]
Hi @luigi311 thanks for the report! We believe this is a bug and will work on getting it fixed up. We'll keep you posted!
