### ISSUE TITLE
get_net_worth() not working

### ISSUE THREAD

**Issue by dzg** [mintapi/mintapi#457]
Using the "2.0 (Pending)" version:
```
>>> mint.get_net_worth()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "___/mintapi/mintapi/api.py", line 311, in get_net_worth
    [
  File "___/mintapi/mintapi/api.py", line 312, in <listcomp>
    -a["currentBalance"] if a["type"] in invert else a["currentBalance"]
KeyError: 'currentBalance'
```

FWIW, `mint.get_account_data()` works fine.

**Comment by burkematthew** [comment]
Thanks @dzg !  Getting this fixed up.

**Comment by dzg** [comment]
#459 fixes `cli.py` ... what about `api.py` ?
