### ISSUE TITLE
`mint.get_credit_score_data()` throws error when outputting to CSV

### ISSUE THREAD

**Issue by dzg** [mintapi/mintapi#468]
```
>>> mint.get_credit_score_data()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/site-packages/mintapi/api.py", line 315, in get_credit_score_data
    report = self.get_credit_report_data(
  File "/usr/local/lib/python3.9/site-packages/mintapi/api.py", line 347, in get_credit_report_data
    credit_report["reports"] = self._get_credit_reports(limit, credit_header)
  File "/usr/local/lib/python3.9/site-packages/mintapi/api.py", line 374, in _get_credit_reports
    return self.get(
  File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 910, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/simplejson/__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.9/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/local/lib/python3.9/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

What version of MintAPI are you using?
2.0

**Comment by burkematthew** [comment]
Thanks @dzg ! We'll take a look and see what's going on.

**Comment by burkematthew** [comment]
@dzg so it looks like what was previously only failing for `--headless` mode is now failing regardless.  We had this logged previously under https://github.com/mintapi/mintapi/issues/349.  The credit-related information is coming from a separate base URL within Mint.  It looks like they may have tightened up some authorization handling at this URL.  What I'm going to do is close this issue as a duplicate and make a comment on the original issue that it's now happening even if not in headless mode.

**Comment by burkematthew** [comment]
That being said, there is another issue when pulling credit score data to CSV.  The following errors occurs:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/matthewburke/github/mintapi/mintapi/cli.py", line 464, in main
    output_data(options, data, constants.CREDIT_SCORE_KEY, attention_msg)
  File "/Users/matthewburke/github/mintapi/mintapi/cli.py", line 329, in output_data
    json_normalize(data).to_csv(filename, index=False)
  File "/usr/local/lib/python3.9/site-packages/pandas/io/json/_normalize.py", line 423, in _json_normalize
    raise NotImplementedError
```

I'll get this fixed.
