### ISSUE TITLE
Hangs on creation 'mint' instance

### ISSUE THREAD

**Issue by system3788** [mintapi/mintapi#486]
Hangs on creation.
It logs in, main screen is loaded and then just hangs.
Page (account) has interface with sidebar menu.

Version: 2.1

```
mint = mintapi.Mint(
	mintEmail,  # Email used to log in to Mint
	mintPasswd,  # Your password used to log in to mint
	# Optional parameters
	mfa_method='soft-token',  # See MFA Methods section
					   # Can be 'sms' (default), 'email', or 'soft-token'.
					   # if mintapi detects an MFA request, it will trigger the requested method
					   # and prompt on the command line.
	mfa_input_callback=None,  # see MFA Methods section
							  # used with mfa_method = 'sms' or 'email'
							  # A callback accepting a single argument (the prompt)
							  # which returns the user-inputted 2FA code. By default
							  # the default Python `input` function is used.
	mfa_token=mfaToken,   # see MFA Methods section
					  # used with mfa_method='soft-token'
					  # the token that is used to generate the totp
	intuit_account=None, # account name when multiple accounts are registered with this email.
	headless=False,  # Whether the chromedriver should work without opening a
					 # visible window (useful for server-side deployments)
						 # None will use the default account.
	session_path=None, # Directory that the Chrome persistent session will be written/read from.
					   # To avoid the 2FA code being asked for multiple times, you can either set
					   # this parameter or log in by hand in Chrome under the same user this runs
					   # as.
	imap_account=imapAcc, # account name used to log in to your IMAP server
	imap_password=imapPasswd, # account password used to log in to your IMAP server
	imap_server=imapServer,  # IMAP server host name
	imap_folder='INBOX',  # IMAP folder that receives MFA email
	wait_for_sync=False,  # do not wait for accounts to sync
	wait_for_sync_timeout=305,  # number of seconds to wait for sync
	use_chromedriver_on_path=True,  # True will use a system provided chromedriver binary that
									 # is on the PATH (instead of downloading the latest version)
	)
accounts = mint.get_accounts()
```

Stacktrace/error received:
```
Timed out!
Traceback (most recent call last):
  File "/home/scrp/.local/lib/python3.9/site-packages/mintapi/api.py", line 235, in login_and_get_token
    self.status_message, self.token = sign_in(
  File "/home/scrp/.local/lib/python3.9/site-packages/mintapi/signIn.py", line 329, in sign_in
    mfa_page(
  File "/home/scrp/.local/lib/python3.9/site-packages/mintapi/signIn.py", line 439, in mfa_page
    mfa_token_input = driver.find_element_by_css_selector(
  File "/usr/local/lib/python3.9/dist-packages/selenium/webdriver/remote/webdriver.py", line 598, in find_element_by_css_selector
    return self.find_element(by=By.CSS_SELECTOR, value=css_selector)
  File "/usr/local/lib/python3.9/dist-packages/selenium/webdriver/remote/webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "/usr/local/lib/python3.9/dist-packages/selenium/webdriver/remote/webdriver.py", line 319, in execute
    response = self.command_executor.execute(driver_command, params)
  File "/usr/local/lib/python3.9/dist-packages/selenium/webdriver/remote/remote_connection.py", line 374, in execute
    return self._request(command_info[0], url, body=data)
  File "/usr/local/lib/python3.9/dist-packages/selenium/webdriver/remote/remote_connection.py", line 397, in _request
    resp = self._conn.request(method, url, body=body, headers=headers)
  File "/usr/lib/python3/dist-packages/urllib3/request.py", line 78, in request
    return self.request_encode_body(
  File "/usr/lib/python3/dist-packages/urllib3/request.py", line 170, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "/usr/lib/python3/dist-packages/urllib3/poolmanager.py", line 375, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.9/http/client.py", line 1347, in getresponse
    response.begin()
  File "/usr/lib/python3.9/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.9/http/client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
```

**Additional context**
Also, looks like option "beta=True" is not working, returns error when using it.

**Comment by burkematthew** [comment]
@system3788 please remove sending `mfa_method` and see if that resolves your issue.

**Comment by system3788** [comment]
> @system3788 please remove sending `mfa_method` and see if that resolves your issue.

Actually we use "soft-token" as mfa_method at this moment (since google disabled less secure apps to log in IMAP).
But it logs in and I see "overview" page with refreshing bar at the bottom of page. Then it syas "Account refresh compleate".
Is there anything else we can try?

**Comment by burkematthew** [comment]
@system3788 it's not the method itself that you'd be removing. MintAPI detects which MFA method it needs to log you in and requests accordingly. The only time you need (or should) submit a value in that argument is if your flow requests for you to select from a list of methods to use. 

Based on what you are saying after you remove the argument, it seems like it is working as expected?

**Comment by system3788** [comment]
Removing mfa_method leads to stop mintapi on screen where 6 digits should be entered.
From outr side we'd like to use soft-token method as predefined. And it successfully loges in into mint account.
But then nothing happens. 
mint.get_accounts() - never retuns values; application rises Time out exception.

**Comment by burkematthew** [comment]
@system3788 if you're on V2 and using get_accounts(), that's one issue as the method is now get_account_data(). Also, on the MFA screen, what is it prompting you for? Email, sms, authenticator, etc.?

**Comment by system3788** [comment]
With get_account_data same thing, just hangs.
MFA screen is for authenticator.

**Comment by burkematthew** [comment]
@system3788 now that you've made a couple modifications, can you paste your script you are running so I can make sure I'm up to speed?

**Comment by system3788** [comment]
```
mint = mintapi.Mint(
mintEmail,  # Email used to log in to Mint
mintPasswd,  # Your password used to log in to mint
# Optional parameters
mfa_method='soft-token',  # See MFA Methods section
				   # Can be 'sms' (default), 'email', or 'soft-token'.
				   # if mintapi detects an MFA request, it will trigger the requested method
				   # and prompt on the command line.
mfa_token=mfaToken,   # see MFA Methods section
				  # used with mfa_method='soft-token'
				  # the token that is used to generate the totp
intuit_account=None, # account name when multiple accounts are registered with this email.
headless=False,  # Whether the chromedriver should work without opening a
				 # visible window (useful for server-side deployments)
					 # None will use the default account.
# session_path=None, 
session_path='sessions', # Directory that the Chrome persistent session will be written/read from.
				   # To avoid the 2FA code being asked for multiple times, you can either set
				   # this parameter or log in by hand in Chrome under the same user this runs
				   # as.
wait_for_sync=False,  # do not wait for accounts to sync
wait_for_sync_timeout=300,  # number of seconds to wait for sync
use_chromedriver_on_path=True,  # True will use a system provided chromedriver binary that
						 # is on the PATH (instead of downloading the latest version)
)
accounts = mint.get_account_data()
```

**Comment by system3788** [comment]
Removing mfa_method leads to stop mintapi on screen where 6 digits should be entered. It does not login automatically.

**Comment by burkematthew** [comment]
@system3788 your Intuit account must be configured to use an authenticator app. You should disable that at your account level if you do not wish to use an authenticator.

**Comment by system3788** [comment]
In this case it will require confirmation code from mailbox, isn't it?
Why can't we use mfa_method='soft-token' with mfa_token for authenticator?
When we use successfully it it logs in.

**Comment by burkematthew** [comment]
@system3788 Submitting a value for mfa_method should not be used with V2 unless you are provided with the screen to select which MFA you want to use. We refactored the login flow so that we identify what is required based on prompts from Mint. You could send mfa_method=email but it doesn't matter if Mint is requesting something other than email. 

I digress...

How long are you waiting before determining that Mint is "hung"?

**Comment by system3788** [comment]
Strange, but it work (logs in) every time we use mfa_method='soft-token'.
Waiting for about 5 min.
Yes it does not return value.

Additional traceback info:
```
Traceback (most recent call last):
  File "/home/scrp/.local/lib/python3.9/site-packages/mintapi/api.py", line 235, in login_and_get_token
    self.status_message, self.token = sign_in(
  File "/home/scrp/.local/lib/python3.9/site-packages/mintapi/signIn.py", line 339, in sign_in
    account_selection_page(driver, intuit_account)
  File "/home/scrp/.local/lib/python3.9/site-packages/mintapi/signIn.py", line 520, in account_selection_page
    select_account = driver.find_element_by_id("ius-mfa-select-account-section")
  File "/usr/local/lib/python3.9/dist-packages/selenium/webdriver/remote/webdriver.py", line 360, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "/usr/local/lib/python3.9/dist-packages/selenium/webdriver/remote/webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "/usr/local/lib/python3.9/dist-packages/selenium/webdriver/remote/webdriver.py", line 319, in execute
    response = self.command_executor.execute(driver_command, params)
  File "/usr/local/lib/python3.9/dist-packages/selenium/webdriver/remote/remote_connection.py", line 374, in execute
    return self._request(command_info[0], url, body=data)
  File "/usr/local/lib/python3.9/dist-packages/selenium/webdriver/remote/remote_connection.py", line 397, in _request
    resp = self._conn.request(method, url, body=body, headers=headers)
  File "/usr/lib/python3/dist-packages/urllib3/request.py", line 78, in request
    return self.request_encode_body(
  File "/usr/lib/python3/dist-packages/urllib3/request.py", line 170, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "/usr/lib/python3/dist-packages/urllib3/poolmanager.py", line 375, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.9/http/client.py", line 1347, in getresponse
    response.begin()
  File "/usr/lib/python3.9/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.9/http/client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
```

**Comment by system3788** [comment]
Now it keeps throwing an error: 
```
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot determine loading status
from unknown error: unexpected command response
```
Full trace:
```
Now it keeps throwing an error: selenium.common.exceptions.WebDriverException: Message: unknown error: cannot determine loading status
from unknown error: unexpected command response
```
