### ISSUE TITLE
The sign in page doesn't load fast enough and the click to sign in fails

### ISSUE THREAD

**Issue by gabefortin** [mintapi/mintapi#492]
**Describe the bug**
Not logging in to Mint. Get error 'selenium.common.exceptions.WebDriverException: Message: unknown error: cannot determine loading status' and Chrome shuts down instantly.

What version of MintAPI are you using?
2.1

What command[s] did you run / steps to reproduce?
Stacktrace/error received:
Message: unknown error: cannot determine loading status
from unknown error: unexpected command response
  (Session info: chrome=103.0.5060.53)
Traceback (most recent call last):
  File "/Users/gabe.fortin/Documents/coding/budgettracker/venv/lib/python3.9/site-packages/mintapi/api.py", line 166, in login_and_get_token
    self.status_message = sign_in(
  File "/Users/gabe.fortin/Documents/coding/budgettracker/venv/lib/python3.9/site-packages/mintapi/signIn.py", line 333, in sign_in
    element.click()
  File "/Users/gabe.fortin/Documents/coding/budgettracker/venv/lib/python3.9/site-packages/selenium/webdriver/remote/webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/Users/gabe.fortin/Documents/coding/budgettracker/venv/lib/python3.9/site-packages/selenium/webdriver/remote/webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "/Users/gabe.fortin/Documents/coding/budgettracker/venv/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/gabe.fortin/Documents/coding/budgettracker/venv/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot determine loading status
from unknown error: unexpected command response
  (Session info: chrome=103.0.5060.53)

Traceback (most recent call last):
  File "/Users/gabe.fortin/Documents/coding/budgettracker/venv/lib/python3.9/site-packages/mintapi/api.py", line 166, in login_and_get_token
    self.status_message = sign_in(
  File "/Users/gabe.fortin/Documents/coding/budgettracker/venv/lib/python3.9/site-packages/mintapi/signIn.py", line 333, in sign_in
    element.click()
  File "/Users/gabe.fortin/Documents/coding/budgettracker/venv/lib/python3.9/site-packages/selenium/webdriver/remote/webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/Users/gabe.fortin/Documents/coding/budgettracker/venv/lib/python3.9/site-packages/selenium/webdriver/remote/webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "/Users/gabe.fortin/Documents/coding/budgettracker/venv/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/gabe.fortin/Documents/coding/budgettracker/venv/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot determine loading status
from unknown error: unexpected command response
  (Session info: chrome=103.0.5060.53)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/gabe.fortin/Documents/coding/budgettracker/mintapitesting.py", line 9, in <module>
    mint = mintapi.Mint('gabeandmartina@gmail.com', 'Yuk0ngeo!')
  File "/Users/gabe.fortin/Documents/coding/budgettracker/venv/lib/python3.9/site-packages/mintapi/api.py", line 95, in __init__
    self.login_and_get_token(
  File "/Users/gabe.fortin/Documents/coding/budgettracker/venv/lib/python3.9/site-packages/mintapi/api.py", line 187, in login_and_get_token
    raise Exception(msg) from e
Exception: Could not sign in to Mint. Current page: https://accounts.intuit.com/index.html?offering_id=Intuit.ifs.mint&namespace_id=50000026&redirect_url=https%3A%2F%2Fmint.intuit.com%2Foverview.event%3Futm_medium%3Ddirect%26cta%3Dnav_login_dropdown%26ivid%3D072194fe-8044-47eb-94e4-debf182448e4

**What did you expect to happen?**
Log on to scrape transactions.
**What actually happened?**
Got error, Chrome closes.
**Additional context**
Was working fine with python code as-is just a few of days ago.

**Comment by burkematthew** [comment]
@gabefortin please include your script that you are running that resulted in this output.

**Comment by CalvinChanCan** [comment]
I'm also experiencing the same issue recently starting on 6/21. For me, I'm just running the following script:

```
client = mintapi.Mint(email=os.getenv('MINT_USERNAME'), password=os.getenv('MINT_PASSWORD'))
```

As I'm debugging, it seems like the issue is occurring on signIn.py on line 333 where `element.click()` gets through to the old username sign in page. But simply adding `time.sleep(1)` before click brings me to the new username sign in page and works as expected. Oddly, I tried using a WebDriverWait before the click but it seems selenium is finding the sign in button but the click isn't. 

```
  if not beta:
      element = driver.find_element_by_link_text("Sign in")
      time.sleep(1)
      element.click()
```

![image](https://user-images.githubusercontent.com/13265811/175457421-8fdd6674-1054-404c-a967-43391da4c6d9.png)

**Comment by dsteiner10** [comment]
I also started getting this error this morning (6/24).  I used CalvinChanCan's approach and the signin worked as expected.
