### ISSUE TITLE
cannot import name 'Opera' from 'selenium.webdriver'

### ISSUE THREAD

**Issue by emann3** [mintapi/mintapi#517]
**Describe the bug**
cannot import name 'Opera' from 'selenium.webdriver'

What version of MintAPI are you using?
the latest release - just did a pip install mintapi --upgrade

What command[s] did you run / steps to reproduce?
any mintapi commmand - even -h

Stacktrace/error received:
PS C:\WINDOWS\system32> mintapi -h
Traceback (most recent call last):
  File "C:\Python310\Scripts\mintapi-script.py", line 33, in <module>
    sys.exit(load_entry_point('mintapi==2.5', 'console_scripts', 'mintapi')())
  File "C:\Python310\Scripts\mintapi-script.py", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "C:\Python310\lib\importlib\metadata\__init__.py", line 162, in load
    module = import_module(match.group('module'))
  File "C:\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Python310\lib\site-packages\mintapi\__init__.py", line 3, in <module>
    from mintapi.api import *
  File "C:\Python310\lib\site-packages\mintapi\api.py", line 6, in <module>
    from mintapi.signIn import sign_in, _create_web_driver_at_mint_com
  File "C:\Python310\lib\site-packages\mintapi\signIn.py", line 27, in <module>
    from seleniumrequests import Chrome
  File "C:\Python310\lib\site-packages\seleniumrequests\__init__.py", line 8, in <module>
    from selenium.webdriver import Opera as _Opera
ImportError: cannot import name 'Opera' from 'selenium.webdriver' (C:\Python310\lib\site-packages\selenium\webdriver\__init__.py)

**Comment by ujjwalkrishna** [comment]
Just upgrade selenium-requests by this command:
`pip install --upgrade selenium-requests`

**Comment by emann3** [comment]
yes, that got me past that issue, thanks.
