### ISSUE TITLE
Unable to proceed past the Account Selection Page: 'WebElement' object is not iterable (Exception: Could not sign in to Mint.)

### ISSUE THREAD

**Issue by emann3** [mintapi/mintapi#518]
**Describe the bug**
get an error logging in

What version of MintAPI are you using?
I used pip3 install git+https://github.com/tsdg112/mintapi.git@master
So I think I am using the latest in MAIN

What command[s] did you run / steps to reproduce?
mintapi -f today --headless --session-path "E:\Server Stuff\sessions" --accounts user pass

Stacktrace/error received:

DevTools listening on ws://127.0.0.1:62556/devtools/browser/0d89d199-a2ca-4105-8264-0e506192c629
[0714/094018.558:INFO:CONSOLE(1)] "analytics performance metrics [object Object]", source: https://mint.intuit.com/handlebars/common_3.0.1271/common/cms/js/csa-init.js (1)
[0714/094018.604:INFO:CONSOLE(1)] "analytics performance metrics [object Object]", source: https://mint.intuit.com/handlebars/common_3.0.1271/common/cms/js/csa-init.js (1)
[0714/094020.723:INFO:CONSOLE(69)] "before load rule ran", source: https://accounts.intuit.com/iux-tealium/utag/intuit/cg-accounts/prod/utag.js (69)
[0714/094020.841:INFO:CONSOLE(1)] "All core plugins started...", source: https://plugin.intuitcdn.net/web-shell/3.258.2/adk/5400.js (1)
[0714/094020.841:INFO:CONSOLE(1)] "Plugins registered...", source: https://plugin.intuitcdn.net/web-shell/3.258.2/adk/5400.js (1)
[0714/094020.857:INFO:CONSOLE(1)] "Application before-ready completed...", source: https://plugin.intuitcdn.net/web-shell/3.258.2/adk/5400.js (1)
[0714/094020.857:INFO:CONSOLE(1)] "Application ready...", source: https://plugin.intuitcdn.net/web-shell/3.258.2/adk/5400.js (1)
[0714/094020.857:INFO:CONSOLE(1)] "default delegate action handler  [object Object]", source: https://plugin.intuitcdn.net/web-shell/3.258.2/adk/342.js (1)
[0714/094020.878:INFO:CONSOLE(1)] "Shell - successfully initialized RUM module [object Object]", source: https://plugin.intuitcdn.net/web-shell/3.258.2/adk/222.js (1)
[0714/094020.894:INFO:CONSOLE(1)] "@ids-ts/theme is being deprecated. Please use @design-systems/theme instead.", source: https://plugin.intuitcdn.net/web-shell/3.258.2/adk/624.js (1)
[0714/094020.894:INFO:CONSOLE(1)] "widget-request-start [object Object]", source: https://plugin.intuitcdn.net/web-shell/3.258.2/adk/222.js (1)
[0714/094020.909:INFO:CONSOLE(1)] "widget-load-start [object Object]", source: https://plugin.intuitcdn.net/web-shell/3.258.2/adk/222.js (1)
[0714/094020.928:INFO:CONSOLE(2)] "Unsatisfied version 3.5.2 of shared singleton module @design-systems/theme (required =3.5.1)", source: https://plugin.intuitcdn.net/identity-authn-core-ui/remoteEntry.4942e53a409866b36362.js (2)
[0714/094020.932:INFO:CONSOLE(2)] "Unsatisfied version 3.5.2 of shared singleton module @design-systems/theme (required =3.5.1)", source: https://plugin.intuitcdn.net/identity-authn-core-ui/remoteEntry.4942e53a409866b36362.js (2)
[0714/094020.938:INFO:CONSOLE(2)] "Unsatisfied version 3.5.2 of shared singleton module @design-systems/theme (required =3.5.1)", source: https://plugin.intuitcdn.net/identity-authn-core-ui/remoteEntry.4942e53a409866b36362.js (2)
[0714/094020.941:INFO:CONSOLE(2)] "Unsatisfied version 3.5.2 of shared singleton module @design-systems/theme (required =3.5.1)", source: https://plugin.intuitcdn.net/identity-authn-core-ui/remoteEntry.4942e53a409866b36362.js (2)
[0714/094020.951:INFO:CONSOLE(2)] "Unsatisfied version 3.5.2 of shared singleton module @design-systems/theme (required =3.5.1)", source: https://plugin.intuitcdn.net/identity-authn-core-ui/remoteEntry.4942e53a409866b36362.js (2)
[0714/094020.952:INFO:CONSOLE(2)] "Unsatisfied version 3.5.2 of shared singleton module @design-systems/theme (required =3.5.1)", source: https://plugin.intuitcdn.net/identity-authn-core-ui/remoteEntry.4942e53a409866b36362.js (2)
[0714/094020.954:INFO:CONSOLE(2)] "Unsatisfied version 3.5.2 of shared singleton module @design-systems/theme (required =3.5.1)", source: https://plugin.intuitcdn.net/identity-authn-core-ui/remoteEntry.4942e53a409866b36362.js (2)
[0714/094020.961:INFO:CONSOLE(2)] "Unsatisfied version 3.5.2 of shared singleton module @design-systems/theme (required =3.5.1)", source: https://plugin.intuitcdn.net/identity-authn-core-ui/remoteEntry.4942e53a409866b36362.js (2)
[0714/094020.964:INFO:CONSOLE(2)] "Unsatisfied version 3.5.2 of shared singleton module @design-systems/theme (required =3.5.1)", source: https://plugin.intuitcdn.net/identity-authn-core-ui/remoteEntry.4942e53a409866b36362.js (2)
[0714/094020.965:INFO:CONSOLE(2)] "Unsatisfied version 3.5.2 of shared singleton module @design-systems/theme (required =3.5.1)", source: https://plugin.intuitcdn.net/identity-authn-core-ui/remoteEntry.4942e53a409866b36362.js (2)
[0714/094020.970:INFO:CONSOLE(2)] "Unsatisfied version 3.5.2 of shared singleton module @design-systems/theme (required =3.5.1)", source: https://plugin.intuitcdn.net/identity-authn-core-ui/remoteEntry.4942e53a409866b36362.js (2)
[0714/094020.975:INFO:CONSOLE(2)] "Unsatisfied version 3.5.2 of shared singleton module @design-systems/theme (required =3.5.1)", source: https://plugin.intuitcdn.net/identity-authn-core-ui/remoteEntry.4942e53a409866b36362.js (2)
[0714/094020.977:INFO:CONSOLE(2)] "Unsatisfied version 3.5.2 of shared singleton module @design-systems/theme (required =3.5.1)", source: https://plugin.intuitcdn.net/identity-authn-core-ui/remoteEntry.4942e53a409866b36362.js (2)
[0714/094020.982:INFO:CONSOLE(2)] "Unsatisfied version 3.5.2 of shared singleton module @design-systems/theme (required =3.5.1)", source: https://plugin.intuitcdn.net/identity-authn-core-ui/remoteEntry.4942e53a409866b36362.js (2)
[0714/094020.988:INFO:CONSOLE(2)] "Unsatisfied version 3.5.2 of shared singleton module @design-systems/theme (required =3.5.1)", source: https://plugin.intuitcdn.net/identity-authn-core-ui/remoteEntry.4942e53a409866b36362.js (2)
[0714/094020.992:INFO:CONSOLE(2)] "Unsatisfied version 3.5.2 of shared singleton module @design-systems/theme (required =3.5.1)", source: https://plugin.intuitcdn.net/identity-authn-core-ui/remoteEntry.4942e53a409866b36362.js (2)
[0714/094021.223:INFO:CONSOLE(1)] "widget-load-end [object Object]", source: https://plugin.intuitcdn.net/web-shell/3.258.2/adk/222.js (1)
[0714/094021.227:INFO:CONSOLE(1)] "widget-mount [object Object]", source: https://plugin.intuitcdn.net/web-shell/3.258.2/adk/222.js (1)
[0714/094021.229:INFO:CONSOLE(1)] "widget-first-display [object Object]", source: https://plugin.intuitcdn.net/web-shell/3.258.2/adk/222.js (1)
[0714/094021.236:INFO:CONSOLE(1)] "widget-ready [object Object]", source: https://plugin.intuitcdn.net/web-shell/3.258.2/adk/222.js (1)
[0714/094021.370:ERROR:stun_port.cc(80)] Binding error response: class=4 number=1 reason=Unauthorized
[0714/094021.650:INFO:CONSOLE(0)] "Autofocus processing was blocked because a document already has a focused element.", source: https://accounts.intuit.com/index.html?offering_id=Intuit.ifs.mint&namespace_id=50000026&redirect_url=https%3A%2F%2Fmint.intuit.com%2Foverview.event%3Futm_medium%3Ddirect%26cta%3Dnav_login_dropdown%26ivid%3D9db8b173-9856-4209-b57c-27445650d91b (0)
[0714/094021.863:INFO:CONSOLE(0)] "Access to XMLHttpRequest at 'chrome-extension://ghbmnnjooekpmoecnnnilnnbdlolhkhi/page_embed_script.js' from origin 'https://accounts.intuit.com' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-untrusted, https.", source: https://accounts.intuit.com/index.html?offering_id=Intuit.ifs.mint&namespace_id=50000026&redirect_url=https%3A%2F%2Fmint.intuit.com%2Foverview.event%3Futm_medium%3Ddirect%26cta%3Dnav_login_dropdown%26ivid%3D9db8b173-9856-4209-b57c-27445650d91b (0)
[0714/094022.036:ERROR:stun_port.cc(80)] Binding error response: class=4 number=1 reason=Unauthorized
[0714/094031.436:ERROR:stun_port.cc(80)] Binding error response: class=4 number=1 reason=Unauthorized
[0714/094032.129:ERROR:stun_port.cc(80)] Binding error response: class=4 number=1 reason=Unauthorized
Please enter your 6-digit MFA code: [0714/094041.540:ERROR:stun_port.cc(80)] Binding error response: class=4 number=1 reason=Unauthorized
[0714/094042.207:ERROR:stun_port.cc(80)] Binding error response: class=4 number=1 reason=Unauthorized
599688
[0714/094051.625:ERROR:stun_port.cc(80)] Binding error response: class=4 number=1 reason=Unauthorized
[0714/094052.285:ERROR:stun_port.cc(80)] Binding error response: class=4 number=1 reason=Unauthorized
'WebElement' object is not iterable
Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\mintapi\signIn.py", line 358, in sign_in
    handle_same_page_username_password(driver, email, password)
  File "C:\Python310\lib\site-packages\mintapi\signIn.py", line 437, in handle_same_page_username_password
    email_input = driver.find_element(By.ID, "ius-userid")
  File "C:\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 857, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 435, in execute
    self.error_handler.check_response(response)
  File "C:\Python310\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[id="ius-userid"]"}
  (Session info: headless chrome=103.0.5060.114)
Stacktrace:
Backtrace:
        Ordinal0 [0x00286463+2188387]
        Ordinal0 [0x0021E461+1762401]
        Ordinal0 [0x00133D78+802168]
        Ordinal0 [0x00161880+989312]
        Ordinal0 [0x00161B1B+989979]
        Ordinal0 [0x0018E912+1173778]
        Ordinal0 [0x0017C824+1099812]
        Ordinal0 [0x0018CC22+1166370]
        Ordinal0 [0x0017C5F6+1099254]
        Ordinal0 [0x00156BE0+945120]
        Ordinal0 [0x00157AD6+948950]
        GetHandleVerifier [0x005271F2+2712546]
        GetHandleVerifier [0x0051886D+2652765]
        GetHandleVerifier [0x0031002A+520730]
        GetHandleVerifier [0x0030EE06+516086]
        Ordinal0 [0x0022468B+1787531]
        Ordinal0 [0x00228E88+1805960]
        Ordinal0 [0x00228F75+1806197]
        Ordinal0 [0x00231DF1+1842673]
        BaseThreadInitThunk [0x774DFA29+25]
        RtlGetAppContainerNamedObjectPath [0x77DC7A9E+286]
        RtlGetAppContainerNamedObjectPath [0x77DC7A6E+238]
        (No symbol) [0x00000000]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\mintapi\signIn.py", line 456, in handle_different_page_username_password
    raise ElementNotVisibleException()
selenium.common.exceptions.ElementNotVisibleException: Message: None

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\mintapi\api.py", line 169, in login_and_get_token
    self.status_message = sign_in(
  File "C:\Python310\lib\site-packages\mintapi\signIn.py", line 365, in sign_in
    handle_different_page_username_password(driver, email)
  File "C:\Python310\lib\site-packages\mintapi\signIn.py", line 467, in handle_different_page_username_password
    for username_element in username_elements:
TypeError: 'WebElement' object is not iterable
[0714/094053.154:ERROR:turn_port.cc(866)] Port[98a300:0:1:0:relay:Net[any:0.0.0.x/0:Wildcard:id=0]]: Failed to send TURN message, error: 10053
Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\mintapi\signIn.py", line 358, in sign_in
    handle_same_page_username_password(driver, email, password)
  File "C:\Python310\lib\site-packages\mintapi\signIn.py", line 437, in handle_same_page_username_password
    email_input = driver.find_element(By.ID, "ius-userid")
  File "C:\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 857, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 435, in execute
    self.error_handler.check_response(response)
  File "C:\Python310\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[id="ius-userid"]"}
  (Session info: headless chrome=103.0.5060.114)
Stacktrace:
Backtrace:
        Ordinal0 [0x00286463+2188387]
        Ordinal0 [0x0021E461+1762401]
        Ordinal0 [0x00133D78+802168]
        Ordinal0 [0x00161880+989312]
        Ordinal0 [0x00161B1B+989979]
        Ordinal0 [0x0018E912+1173778]
        Ordinal0 [0x0017C824+1099812]
        Ordinal0 [0x0018CC22+1166370]
        Ordinal0 [0x0017C5F6+1099254]
        Ordinal0 [0x00156BE0+945120]
        Ordinal0 [0x00157AD6+948950]
        GetHandleVerifier [0x005271F2+2712546]
        GetHandleVerifier [0x0051886D+2652765]
        GetHandleVerifier [0x0031002A+520730]
        GetHandleVerifier [0x0030EE06+516086]
        Ordinal0 [0x0022468B+1787531]
        Ordinal0 [0x00228E88+1805960]
        Ordinal0 [0x00228F75+1806197]
        Ordinal0 [0x00231DF1+1842673]
        BaseThreadInitThunk [0x774DFA29+25]
        RtlGetAppContainerNamedObjectPath [0x77DC7A9E+286]
        RtlGetAppContainerNamedObjectPath [0x77DC7A6E+238]
        (No symbol) [0x00000000]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\mintapi\signIn.py", line 456, in handle_different_page_username_password
    raise ElementNotVisibleException()
selenium.common.exceptions.ElementNotVisibleException: Message: None

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\mintapi\api.py", line 169, in login_and_get_token
    self.status_message = sign_in(
  File "C:\Python310\lib\site-packages\mintapi\signIn.py", line 365, in sign_in
    handle_different_page_username_password(driver, email)
  File "C:\Python310\lib\site-packages\mintapi\signIn.py", line 467, in handle_different_page_username_password
    for username_element in username_elements:
TypeError: 'WebElement' object is not iterable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Python310\Scripts\mintapi-script.py", line 33, in <module>
    sys.exit(load_entry_point('mintapi==2.5', 'console_scripts', 'mintapi')())
  File "C:\Python310\lib\site-packages\mintapi\cli.py", line 417, in main
    mint = Mint(
  File "C:\Python310\lib\site-packages\mintapi\api.py", line 96, in __init__
    self.login_and_get_token(
  File "C:\Python310\lib\site-packages\mintapi\api.py", line 191, in login_and_get_token
    raise Exception(msg) from e
Exception: Could not sign in to Mint. Current page: https://accounts.intuit.com/index.html?offering_id=Intuit.ifs.mint&namespace_id=50000026&redirect_url=https%3A%2F%2Fmint.intuit.com%2Foverview.event%3Futm_medium%3Ddirect%26cta%3Dnav_login_dropdown%26ivid%3D9db8b173-9856-4209-b57c-27445650d91b

**Comment by emann3** [comment]
this was solved by one of the fixes recently added to main.

But on main, I am now getting the MFA loop timeout issue - I added a comment to that issue

**Comment by emann3** [comment]
spoke too soon...still getting this error

**Comment by emann3** [comment]
changed to using the bump-selenium-requests branch, same error.

more digging, turning off headless, the error occurs while chrome is on the "pick which account" page

(I have two...would love to get rid of one, but haven't figured out how yet - i don't need the second, I believe its from quicken which I haven't used in years since i found this api)

**Comment by emann3** [comment]
the radio button is correct (but i believe it is selected by default).  the error occurs I assume trying to click the button

**Comment by felciano** [comment]
I just started seeing this as well

**Comment by felciano** [comment]
@jprouty possibly related to https://github.com/jprouty/mint-amazon-tagger/issues/111?

**Comment by emann3** [comment]
@burkematthew the linked PR worked for me - fantastic, thanks VERY much

**Comment by felciano** [comment]
Seems to have resolved the issue for me as well -- thank you @burkematthew!
