### ISSUE TITLE
Mint login failure: timeout in Multifactor Method Loop

### ISSUE THREAD

**Issue by ianvanhoven** [mintapi/mintapi#535]
Started yesterday afternoon...

`[ivh@ci] ./wx.ad.mnt.py ro`
`Login to Mint failed due to timeout in the Multifactor Method Loop`
`Traceback (most recent call last):`
 ` File "/usr/local/lib/python3.8/dist-packages/mintapi/signIn.py", line 401, in sign_in`
  `  WebDriverWait(driver, 5).until(`
  `File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/support/wait.py", line 90, in until`
  `  raise TimeoutException(message, screen, stacktrace)`
`selenium.common.exceptions.TimeoutException: Message:`

`During handling of the above exception, another exception occurred:`

`Traceback (most recent call last):`
 ` File "/usr/local/lib/python3.8/dist-packages/mintapi/api.py", line 169, in login_and_get_token`
  `  self.status_message = sign_in(`
  `File "/usr/local/lib/python3.8/dist-packages/mintapi/signIn.py", line 407, in sign_in`
   ` raise RuntimeError(`
`RuntimeError: Login to Mint failed due to timeout in the Multifactor Method Loop`

**Comment by ianvanhoven** [comment]
Anyone else experiencing this?

Here's my setup:

`% pip show mintapi`
`Name: mintapi`
`Version: 2.7`

`% pip show selenium`
`Name: selenium`
`Version: 4.4.0`

`% apt list -a google-chrome-stable`
`Listing... Done`
`google-chrome-stable/stable,now 104.0.5112.79-1 amd64 [installed]`

`% ll`
`lrwxrwxrwx 1 root root  38 Aug 15 20:34 chromedriver -> rls/chromedriver_linux64_104.0.5112.79*`
`dr-x------ 2 ivh  wx   138 Aug 15 20:34 rls/`

Still getting the `timeout in the Multifactor Method Loop` errors, since late last week.

Any help appreciated!

**Comment by ianvanhoven** [comment]
I was able to workaround this by enabling MFA; closing this issue.
