### ISSUE TITLE
Exception: Could not sign in to Mint.

### ISSUE THREAD

**Issue by pdeangelo** [mintapi/mintapi#550]
Hello,

I have been using this for a few months now with no problem, but all of a sudden I am getting this error:

Traceback (most recent call last):
  File "C:/Users/pdean/AppData/Local/Programs/Python/Python310/M2.py", line 2, in <module>
    mint = mintapi.Mint(
  File "C:\Users\pdean\AppData\Local\Programs\Python\Python310\lib\site-packages\mintapi\api.py", line 122, in __init__
    self.login_and_get_token(
  File "C:\Users\pdean\AppData\Local\Programs\Python\Python310\lib\site-packages\mintapi\api.py", line 217, in login_and_get_token
    raise Exception(msg) from e
Exception: Could not sign in to Mint. Current page: https://accounts.intuit.com/index.html?offering_id=Intuit.ifs.mint&namespace_id=50000026&redirect_url=https%3A%2F%2Fmint.intuit.com%2Foverview.event%3Futm_medium%3Ddirect%26cta%3Dnav_login_dropdown%26ivid%3Ded62fce9-8bd8-4e2b-82bb-a7f9df1f758a

I would appreciate any help!  
Also is there a place where I can donate for this project, it is great!

Thanks,

Paul

**Comment by pdeangelo** [comment]
I read through some of the other issues and added this to signin and it worked
"ius-hosted-ui-main-container"
