### ISSUE TITLE
Exception: Could not sign in to Mint.

### ISSUE THREAD

**Issue by matt199x** [mintapi/mintapi#554]
This new error message is happening to me. It happens with or without a # in front of mfa_method='sms'
Just upgraded to 2.8. 

What version of MintAPI are you using? 2.8
What command[s] did you run / steps to reproduce?:
```
mint = mintapi.Mint('email@gmail.com',
                    mypass,
                    mfa_method='sms',
                    headless=True,
                    use_chromedriver_on_path=True,
                    mfa_input_callback=None,
                    #session_path='/home/pi/mintapi-main/SessionFiles',
                    session_path=None,
                    # Directory that the Chrome persistent session will be written/read from.
                    # To avoid the 2FA code being asked for multiple times, you can either set
                    # this parameter or log in by hand in Chrome under the same user this runs
                    # as.
                    wait_for_sync=False,  # do not wait for accounts to sync
                    wait_for_sync_timeout=300,  # number of seconds to wait for sync
                    
                    )
```

Stacktrace/error received:

```
`Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/mintapi/api.py", line 195, in login_and_get_token
    self.status_message = sign_in(
  File "/usr/local/lib/python3.9/dist-packages/mintapi/signIn.py", line 351, in sign_in
    WebDriverWait(driver, 20).until(
  File "/usr/local/lib/python3.9/dist-packages/selenium/webdriver/support/wait.py", line 90, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x000000954764 <unknown>
#1 0x00000075ccc8 <unknown>
#2 0x000000792108 <unknown>
#3 0x0000007923fc <unknown>
#4 0x0000007c34a4 <unknown>
#5 0x0000007af0f0 <unknown>
#6 0x0000007c1360 <unknown>
#7 0x0000007aef74 <unknown>
#8 0x000000785f48 <unknown>
#9 0x000000786fb0 <unknown>
#10 0x0000009994b8 <unknown>
#11 0x00000099bb58 <unknown>
#12 0x00000099b5e0 <unknown>
#13 0x00000099c1b0 <unknown>
#14 0x000000984210 <unknown>
#15 0x00000099c478 <unknown>
#16 0x0000009793d4 <unknown>
#17 0x0000009b6000 <unknown>
#18 0x0000009b6170 <unknown>
#19 0x0000009d0994 <unknown>
#20 0x000076ea4310 <unknown>
#21 0x000000000000 <unknown>


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/pi/BalanceUpdater-stripped.py", line 57, in <module>
    mint = mintapi.Mint('email@gmail.com',
  File "/usr/local/lib/python3.9/dist-packages/mintapi/api.py", line 122, in __init__
    self.login_and_get_token(
  File "/usr/local/lib/python3.9/dist-packages/mintapi/api.py", line 217, in login_and_get_token
    raise Exception(msg) from e
Exception: Could not sign in to Mint. Current page: https://accounts.intuit.com/index.html?offering_id=Intuit.ifs.mint&namespace_id=50000026&redirect_url=https%3A%2F%2Fmint.intuit.com%2Foverview.event%3Futm_medium%3Ddirect%26cta%3Dnav_login_dropdown%26ivid%3D1462fac2-8ca4-4715-8c24-b1beb77b4f7d`

```

**Comment by hmqk1995** [comment]
same issue

**Comment by apiology** [comment]
@hmqk1995 and @matt199x, could you try the fix in https://github.com/mintapi/mintapi/pull/552 ?  It has been merged, but not yet published, but you can install either off of the main branch here or from my old feature branch:

```
pip uninstall mintapi && pip install git+https://github.com/apiology/mintapi.git@account_selection_css_alternative
```

**Comment by gabefortin** [comment]
@apiology the fix worked for me in getting me through the login but now when I try to get transactions I get the following error: Traceback (most recent call last):
  File "/Users/gabe.fortin/Documents/coding/budgettracker/mintapitesting.py", line 13, in <module>
    df = mint.get_transaction_data(limit=100000)
  File "/Users/gabe.fortin/Documents/coding/budgettracker/venv/lib/python3.9/site-packages/mintapi/api.py", line 603, in get_transaction_data
    data = self.get_data(constants.POST_METHOD, constants.TRANSACTION_KEY, payload)
  File "/Users/gabe.fortin/Documents/coding/budgettracker/venv/lib/python3.9/site-packages/mintapi/api.py", line 240, in get_data
    data = self.__post_mint_endpoint(endpoint, payload)
  File "/Users/gabe.fortin/Documents/coding/budgettracker/venv/lib/python3.9/site-packages/mintapi/api.py", line 459, in __post_mint_endpoint
    response = self.post(
  File "/Users/gabe.fortin/Documents/coding/budgettracker/venv/lib/python3.9/site-packages/mintapi/api.py", line 165, in post
    return self.driver.request("POST", url, **kwargs)
  File "/Users/gabe.fortin/Documents/coding/budgettracker/venv/lib/python3.9/site-packages/seleniumrequests/request.py", line 159, in request
    self.requests_session.headers = get_webdriver_request_headers(self, proxy_host=self.__proxy_host)
  File "/Users/gabe.fortin/Documents/coding/budgettracker/venv/lib/python3.9/site-packages/seleniumrequests/request.py", line 76, in get_webdriver_request_headers
    webdriver.switch_to.window(original_window_handle)
  File "/Users/gabe.fortin/Documents/coding/budgettracker/venv/lib/python3.9/site-packages/selenium/webdriver/remote/switch_to.py", line 134, in window
    self._w3c_window(window_name)
  File "/Users/gabe.fortin/Documents/coding/budgettracker/venv/lib/python3.9/site-packages/selenium/webdriver/remote/switch_to.py", line 142, in _w3c_window
    send_handle(window_name)
  File "/Users/gabe.fortin/Documents/coding/budgettracker/venv/lib/python3.9/site-packages/selenium/webdriver/remote/switch_to.py", line 138, in send_handle
    self._driver.execute(Command.SWITCH_TO_WINDOW, {'handle': h})
  File "/Users/gabe.fortin/Documents/coding/budgettracker/venv/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 429, in execute
    self.error_handler.check_response(response)
  File "/Users/gabe.fortin/Documents/coding/budgettracker/venv/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py", line 243, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: disconnected: received Inspector.detached event
  (Session info: chrome=106.0.5249.119)
Stacktrace:
0   chromedriver                        0x00000001035cd598 chromedriver + 4404632
1   chromedriver                        0x0000000103554fa3 chromedriver + 3911587
2   chromedriver                        0x0000000103201e6a chromedriver + 425578
3   chromedriver                        0x00000001031ef7ec chromedriver + 350188
4   chromedriver                        0x00000001031ef29a chromedriver + 348826
5   chromedriver                        0x00000001031ee717 chromedriver + 345879
6   chromedriver                        0x00000001031ee572 chromedriver + 345458
7   chromedriver                        0x00000001031ed4ca chromedriver + 341194
8   chromedriver                        0x00000001031ed862 chromedriver + 342114
9   chromedriver                        0x00000001031ecd51 chromedriver + 339281
10  chromedriver                        0x00000001031f36cf chromedriver + 366287
11  chromedriver                        0x00000001031ecd06 chromedriver + 339206
12  chromedriver                        0x00000001031ee1ce chromedriver + 344526
13  chromedriver                        0x00000001031ed4ca chromedriver + 341194
14  chromedriver                        0x00000001031ed862 chromedriver + 342114
15  chromedriver                        0x00000001031ecd51 chromedriver + 339281
16  chromedriver                        0x00000001031e71ba chromedriver + 315834
17  chromedriver                        0x00000001031ecd06 chromedriver + 339206
18  chromedriver                        0x00000001031ec3d2 chromedriver + 336850
19  chromedriver                        0x00000001031ec0a0 chromedriver + 336032
20  chromedriver                        0x00000001032034f2 chromedriver + 431346
21  chromedriver                        0x00000001031e09da chromedriver + 289242
22  chromedriver                        0x00000001031e0cd8 chromedriver + 290008
23  chromedriver                        0x0000000103263509 chromedriver + 824585
24  chromedriver                        0x0000000103257d68 chromedriver + 777576
25  chromedriver                        0x000000010322cced chromedriver + 601325
26  chromedriver                        0x000000010322de51 chromedriver + 605777
27  chromedriver                        0x000000010359d0ce chromedriver + 4206798
28  chromedriver                        0x00000001035a1797 chromedriver + 4224919
29  chromedriver                        0x00000001035a8a4f chromedriver + 4254287
30  chromedriver                        0x00000001035a24da chromedriver + 4228314
31  chromedriver                        0x000000010357b23f chromedriver + 4067903
32  chromedriver                        0x00000001035bf6a8 chromedriver + 4347560
33  chromedriver                        0x00000001035bf816 chromedriver + 4347926
34  chromedriver                        0x00000001035d48fe chromedriver + 4434174
35  libsystem_pthread.dylib             0x00007ff8183f84e1 _pthread_start + 125
36  libsystem_pthread.dylib             0x00007ff8183f3f6b thread_start + 15


Process finished with exit code 1

**Comment by ianvanhoven** [comment]
@apiology fix worked, including account balances; not sure about "transactions" (apropos of @gabefortin post)

**Comment by mrooney** [comment]
Thanks for the confirmations!

**Comment by ddollar** [comment]
This fix is not working for me. This is what I get:

```
Mint sync apparently incomplete after timeout.  Data retrieved may not be current.
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.9/dist-packages/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.9/dist-packages/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.9/http/client.py", line 1347, in getresponse
    response.begin()
  File "/usr/lib/python3.9/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.9/http/client.py", line 276, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response
```
