### ISSUE TITLE
Login to Mint failed due to timeout in the Multifactor Method Loop

### ISSUE THREAD

**Issue by dantheman84** [mintapi/mintapi#555]
**Describe the bug**
Stuck at login screen using MFA soft token and headless, trying to pull accounts.

What version of MintAPI are you using? 2.8
What command[s] did you run / steps to reproduce?

ran this from cmd line in windows 10

mintapi --headless --mfa-method soft-token --mfa-token XTokenHereX --accounts --filename "C:\Temp\Dan" --keyring myemail@email.com

Stacktrace/error received:

DevTools listening on ws://127.0.0.1:60525/devtools/browser/10f926ed-0ab4-4d74-8ba6-df8ab233a1b3
[1017/115459.724:INFO:CONSOLE(1)] "analytics performance metrics [object Object]", source: https://mint.intuit.com/handlebars/common_3.0.1288/common/cms/js/csa-init.js (1)
[1017/115459.743:INFO:CONSOLE(1)] "analytics performance metrics [object Object]", source: https://mint.intuit.com/handlebars/common_3.0.1288/common/cms/js/csa-init.js (1)
[1017/115501.206:INFO:CONSOLE(69)] "before load rule ran", source: https://accounts.intuit.com/iux-tealium/utag/intuit/cg-accounts/prod/utag.js (69)
[1017/115501.536:INFO:CONSOLE(1)] "All core plugins started...", source: https://plugin.intuitcdn.net/web-shell/3.295.0/adk/5400.js (1)
[1017/115501.541:INFO:CONSOLE(1)] "Plugins registered...", source: https://plugin.intuitcdn.net/web-shell/3.295.0/adk/5400.js (1)
[1017/115501.544:INFO:CONSOLE(1)] "Application before-ready completed...", source: https://plugin.intuitcdn.net/web-shell/3.295.0/adk/5400.js (1)
[1017/115501.546:INFO:CONSOLE(1)] "Application ready...", source: https://plugin.intuitcdn.net/web-shell/3.295.0/adk/5400.js (1)
[1017/115501.547:INFO:CONSOLE(1)] "default delegate action handler  [object Object]", source: https://plugin.intuitcdn.net/web-shell/3.295.0/adk/9446.js (1)
[1017/115501.587:INFO:CONSOLE(1)] "Shell - successfully initialized RUM module [object Object]", source: https://plugin.intuitcdn.net/web-shell/3.295.0/adk/222.js (1)
[1017/115501.605:INFO:CONSOLE(1)] "@ids-ts/theme is being deprecated. Please use @design-systems/theme instead.", source: https://plugin.intuitcdn.net/web-shell/3.295.0/adk/624.js (1)
[1017/115501.613:INFO:CONSOLE(1)] "widget-request-start [object Object]", source: https://plugin.intuitcdn.net/web-shell/3.295.0/adk/222.js (1)
[1017/115501.615:INFO:CONSOLE(1)] "widget-load-start [object Object]", source: https://plugin.intuitcdn.net/web-shell/3.295.0/adk/222.js (1)
[1017/115501.633:INFO:CONSOLE(2)] "Unsatisfied version 3.5.2 of shared singleton module @design-systems/theme (required =3.4.10)", source: https://plugin.intuitcdn.net/identity-authn-core-ui/remoteEntry.68c24f2f36e559f5f985.js (2)
[1017/115501.674:INFO:CONSOLE(2)] "Unsatisfied version 7.7.1 of shared singleton module @appfabric/web-shell-core/widgets/BaseWidget (required =7.2.1)", source: https://plugin.intuitcdn.net/identity-authn-core-ui/remoteEntry.68c24f2f36e559f5f985.js (2)
[1017/115501.888:INFO:CONSOLE(1)] "widget-load-end [object Object]", source: https://plugin.intuitcdn.net/web-shell/3.295.0/adk/222.js (1)
[1017/115501.935:INFO:CONSOLE(1)] "widget-mount [object Object]", source: https://plugin.intuitcdn.net/web-shell/3.295.0/adk/222.js (1)
[1017/115501.938:INFO:CONSOLE(1)] "widget-first-display [object Object]", source: https://plugin.intuitcdn.net/web-shell/3.295.0/adk/222.js (1)
[1017/115501.939:INFO:CONSOLE(1)] "widget-ready [object Object]", source: https://plugin.intuitcdn.net/web-shell/3.295.0/adk/222.js (1)
[1017/115502.099:ERROR:stun_port.cc(78)] Binding error response: class=4 number=1 reason=Unauthorized
[1017/115502.664:ERROR:stun_port.cc(78)] Binding error response: class=4 number=1 reason=Unauthorized
[1017/115512.157:ERROR:stun_port.cc(78)] Binding error response: class=4 number=1 reason=Unauthorized
Login to Mint failed due to timeout in the Multifactor Method Loop
Traceback (most recent call last):
  File "c:\python39\lib\site-packages\mintapi\signIn.py", line 411, in sign_in
    WebDriverWait(driver, 5).until(
  File "C:\Users\Administrator\AppData\Roaming\Python\Python39\site-packages\selenium\webdriver\support\wait.py", line 90, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\python39\lib\site-packages\mintapi\api.py", line 195, in login_and_get_token
    self.status_message = sign_in(
  File "c:\python39\lib\site-packages\mintapi\signIn.py", line 417, in sign_in
    raise RuntimeError(
RuntimeError: Login to Mint failed due to timeout in the Multifactor Method Loop
[1017/120002.181:ERROR:socket_tcp.cc(328)] Error when reading from TCP socket: -101
[1017/120340.531:ERROR:socket_tcp.cc(328)] Error when reading from TCP socket: -101
Traceback (most recent call last):
  File "c:\python39\lib\site-packages\mintapi\signIn.py", line 411, in sign_in
    WebDriverWait(driver, 5).until(
  File "C:\Users\Administrator\AppData\Roaming\Python\Python39\site-packages\selenium\webdriver\support\wait.py", line 90, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\python39\lib\site-packages\mintapi\api.py", line 195, in login_and_get_token
    self.status_message = sign_in(
  File "c:\python39\lib\site-packages\mintapi\signIn.py", line 417, in sign_in
    raise RuntimeError(
RuntimeError: Login to Mint failed due to timeout in the Multifactor Method Loop

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Python39\Scripts\mintapi-script.py", line 33, in <module>
    sys.exit(load_entry_point('mintapi==2.8', 'console_scripts', 'mintapi')())
  File "c:\python39\lib\site-packages\mintapi\cli.py", line 465, in main
    mint = Mint(
  File "c:\python39\lib\site-packages\mintapi\api.py", line 122, in __init__
    self.login_and_get_token(
  File "c:\python39\lib\site-packages\mintapi\api.py", line 217, in login_and_get_token
    raise Exception(msg) from e
Exception: Could not sign in to Mint. Current page: https://accounts.intuit.com/index.html?offering_id=Intuit.ifs.mint&namespace_id=50000026&redirect_url=https%3A%2F%2Fmint.intuit.com%2Foverview.event%3Futm_medium%3Ddirect%26cta%3Dnav_login_dropdown%26ivid%3D0b25a45d-0388-4783-9ea2-a3a93518b3c5%3Futm_medium%3Ddirect%3Futm_medium%3Ddirect

**Comment by mrooney** [comment]
Resolved via #552
