### ISSUE TITLE
Logs in automatically but crashes after the account refreshes and the accounts file is supposed to be created

### ISSUE THREAD

**Issue by dantheman84** [mintapi/mintapi#565]
Logs in automatically but crashes after the account refreshes and the accounts file is supposed to be created.

What version of MintAPI are you using? 2.8
What command[s] did you run / steps to reproduce?

ran this from cmd line in windows 10

mintapi --headless --mfa-method soft-token --mfa-token XTokenHereX --accounts --filename "C:\Temp\Dan" --keyring [myemail@email.com](mailto:myemail@email.com)

Stacktrace/error received:

DevTools listening on ws://127.0.0.1:55498/devtools/browser/adedfc55-9542-46de-af23-c60478a1a22a
[110468:110540:1031/224918.519:ERROR:device_event_log_impl.cc(215)] [22:49:18.519] USB: usb_device_handle_win.cc:1048 Failed to read descriptor from node connection: A device attached to the system is not functioning. (0x1F)
[110468:110540:1031/224918.519:ERROR:device_event_log_impl.cc(215)] [22:49:18.520] USB: usb_device_handle_win.cc:1048 Failed to read descriptor from node connection: A device attached to the system is not functioning. (0x1F)
[110468:110540:1031/225006.843:ERROR:interface_endpoint_client.cc(690)] Message 0 rejected by interface blink.mojom.WidgetHost
Traceback (most recent call last):
  File "c:\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Python39\Scripts\mintapi.exe\__main__.py", line 7, in <module>
  File "c:\python39\lib\site-packages\mintapi\cli.py", line 518, in main
    data = mint.get_account_data(limit=options.limit)
  File "c:\python39\lib\site-packages\mintapi\api.py", line 262, in get_account_data
    return self.get_data(
  File "c:\python39\lib\site-packages\mintapi\api.py", line 242, in get_data
    data = self.__get_mint_endpoint(endpoint, **kwargs)
  File "c:\python39\lib\site-packages\mintapi\api.py", line 449, in __get_mint_endpoint
    response = self.get(
  File "c:\python39\lib\site-packages\mintapi\api.py", line 162, in get
    return self.driver.request("GET", url, **kwargs)
  File "C:\Users\Administrator\AppData\Roaming\Python\Python39\site-packages\seleniumrequests\request.py", line 159, in request
    self.requests_session.headers = get_webdriver_request_headers(self, proxy_host=self.__proxy_host)
  File "C:\Users\Administrator\AppData\Roaming\Python\Python39\site-packages\seleniumrequests\request.py", line 76, in get_webdriver_request_headers
    webdriver.switch_to.window(original_window_handle)
  File "C:\Users\Administrator\AppData\Roaming\Python\Python39\site-packages\selenium\webdriver\remote\switch_to.py", line 134, in window
    self._w3c_window(window_name)
  File "C:\Users\Administrator\AppData\Roaming\Python\Python39\site-packages\selenium\webdriver\remote\switch_to.py", line 142, in _w3c_window
    send_handle(window_name)
  File "C:\Users\Administrator\AppData\Roaming\Python\Python39\site-packages\selenium\webdriver\remote\switch_to.py", line 138, in send_handle
    self._driver.execute(Command.SWITCH_TO_WINDOW, {'handle': h})
  File "C:\Users\Administrator\AppData\Roaming\Python\Python39\site-packages\selenium\webdriver\remote\webdriver.py", line 429, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Administrator\AppData\Roaming\Python\Python39\site-packages\selenium\webdriver\remote\errorhandler.py", line 243, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: No target with given id found
  (Session info: chrome=107.0.5304.88)
Stacktrace:
Backtrace:
        Ordinal0 [0x0060ACD3+2075859]
        Ordinal0 [0x0059EE61+1633889]
        Ordinal0 [0x0049B7BD+571325]
        Ordinal0 [0x0048E9CF+518607]
        Ordinal0 [0x0048D2A3+512675]
        Ordinal0 [0x0048D6D8+513752]
        Ordinal0 [0x0048D668+513640]
        Ordinal0 [0x0048289F+469151]
        Ordinal0 [0x00481FB0+466864]
        Ordinal0 [0x004823CC+467916]
        Ordinal0 [0x004F13D9+922585]
        Ordinal0 [0x004E72E3+881379]
        Ordinal0 [0x004BFEFD+720637]
        Ordinal0 [0x004C0F3F+724799]
        GetHandleVerifier [0x008BEED2+2769538]
        GetHandleVerifier [0x008B0D95+2711877]
        GetHandleVerifier [0x0069A03A+521194]
        GetHandleVerifier [0x00698DA0+516432]
        Ordinal0 [0x005A682C+1665068]
        Ordinal0 [0x005AB128+1683752]
        Ordinal0 [0x005AB215+1683989]
        Ordinal0 [0x005B6484+1729668]
        BaseThreadInitThunk [0x76EAFA29+25]
        RtlGetAppContainerNamedObjectPath [0x76FF7BBE+286]
        RtlGetAppContainerNamedObjectPath [0x76FF7B8E+238]

**Comment by mrooney** [comment]
I just released mintapi 2.10 to pypi, which updates selenium-requests to 2.0.1. Please try that (or update your selenium-requests to the same) and let me know if that resolves the issue. Thanks!

**Comment by EECDieter** [comment]
Hey @mrooney. Just tested twice, and confirmed issue is resolved. Thanks much.

**Comment by dstapel** [comment]
Hey @mrooney. Posted from wrong account. Tested twice, and issue resolved. Thanks again.

**Comment by mrooney** [comment]
Awesome, thanks for confirming!
