### ISSUE TITLE
Can't get past "RuntimeError: Login to Mint failed due to timeout in the Multifactor Method Loop"

### ISSUE THREAD

**Issue by Crazee** [mintapi/mintapi#572]
**Describe the bug**
Made a new Mint account that just has an email address, no phone number.  And an email address just for you.  But everything I try, with adding "--imap-server" etc. didn't help.

What version of MintAPI are you using?

Docker.  Can't tell what version because there is no "mintapi --version".

What command[s] did you run / steps to reproduce?
Last one was:
time docker run  ghcr.io/mintapi/mintapi mintapi xxxx@murena.io xxxxpw --headless --use-chromedriver-on-path --mfa-method email -t --imap-account xxxx@murena.io --imap-password xxxxpw --imap-server mail.ecloud.global

Stacktrace/error received:
Login to Mint failed due to timeout in the Multifactor Method Loop
Traceback (most recent call last):
  File "/home/seluser/.local/lib/python3.8/site-packages/mintapi/signIn.py", line 411, in sign_in
    WebDriverWait(driver, 5).until(
  File "/home/seluser/.local/lib/python3.8/site-packages/selenium/webdriver/support/wait.py", line 95, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/seluser/.local/lib/python3.8/site-packages/mintapi/api.py", line 195, in login_and_get_token
    self.status_message = sign_in(
  File "/home/seluser/.local/lib/python3.8/site-packages/mintapi/signIn.py", line 417, in sign_in
    raise RuntimeError(
RuntimeError: Login to Mint failed due to timeout in the Multifactor Method Loop
Traceback (most recent call last):
  File "/home/seluser/.local/lib/python3.8/site-packages/mintapi/signIn.py", line 411, in sign_in
    WebDriverWait(driver, 5).until(
  File "/home/seluser/.local/lib/python3.8/site-packages/selenium/webdriver/support/wait.py", line 95, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/seluser/.local/lib/python3.8/site-packages/mintapi/api.py", line 195, in login_and_get_token
    self.status_message = sign_in(
  File "/home/seluser/.local/lib/python3.8/site-packages/mintapi/signIn.py", line 417, in sign_in
    raise RuntimeError(
RuntimeError: Login to Mint failed due to timeout in the Multifactor Method Loop

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/seluser/.local/bin/mintapi", line 8, in <module>
    sys.exit(main())
  File "/home/seluser/.local/lib/python3.8/site-packages/mintapi/cli.py", line 465, in main
    mint = Mint(
  File "/home/seluser/.local/lib/python3.8/site-packages/mintapi/api.py", line 122, in __init__
    self.login_and_get_token(
  File "/home/seluser/.local/lib/python3.8/site-packages/mintapi/api.py", line 217, in login_and_get_token
    raise Exception(msg) from e
Exception: Could not sign in to Mint. Current page: https://accounts.intuit.com/index.html?offering_id=Intuit.ifs.mint&namespace_id=50000026&redirect_url=https%3A%2F%2Fmint.intuit.com%2Foverview.event%3Futm_medium%3Ddirect%26cta%3Dnav_login_dropdown%26ivid%3De44a0a22-ed69-4d0b-9daa-cfbe2d2bc267

**What did you expect to happen?**
Get output of transaction data as JSON.

**What actually happened?**
See stacktrace.  The email account does get the verification email.

**Additional context**

**Comment by EmpireConsultants** [comment]
Had the same issue. First time was because I didn't have TFA setup on my intuit account. I added my phone and got the prompt. After I did that, I added an authenticator add to the TFA and it made that my primary. Again I tried mintapi and got the the error. So apparently you can't have an authenticator app as your TFA.
