### ISSUE TITLE
(unknown error: DevToolsActivePort file doesn't exist)

### ISSUE THREAD

**Issue by Crazee** [mintapi/mintapi#573]
**Describe the bug**
Ubuntu 22.04.  Installed pip, chromium from snap, "pip install 'mintapi>=2.0'".

What version of MintAPI are you using?
2.10

What command[s] did you run / steps to reproduce?
mintapi --keyring --headless

Stacktrace/error received:
/usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.13) or chardet (3.0.4) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
Mint e-mail: xxxx@murena.io
Mint password: 
Traceback (most recent call last):
  File "/home/ggr/.local/bin/mintapi", line 8, in <module>
    sys.exit(main())
  File "/home/ggr/.local/lib/python3.8/site-packages/mintapi/cli.py", line 465, in main
    mint = Mint(
  File "/home/ggr/.local/lib/python3.8/site-packages/mintapi/api.py", line 122, in __init__
    self.login_and_get_token(
  File "/home/ggr/.local/lib/python3.8/site-packages/mintapi/api.py", line 190, in login_and_get_token
    self.driver = driver or _create_web_driver_at_mint_com(
  File "/home/ggr/.local/lib/python3.8/site-packages/mintapi/signIn.py", line 313, in _create_web_driver_at_mint_com
    driver = Chrome(
  File "/home/ggr/.local/lib/python3.8/site-packages/seleniumrequests/request.py", line 146, in __init__
    super(RequestsSessionMixin, self).__init__(*args, **kwargs)
  File "/home/ggr/.local/lib/python3.8/site-packages/selenium/webdriver/chrome/webdriver.py", line 81, in __init__
    super().__init__(
  File "/home/ggr/.local/lib/python3.8/site-packages/selenium/webdriver/chromium/webdriver.py", line 106, in __init__
    super().__init__(
  File "/home/ggr/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 288, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/ggr/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 381, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/ggr/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 444, in execute
    self.error_handler.check_response(response)
  File "/home/ggr/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 249, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: crashed.
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /snap/bin/chromium is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
Stacktrace:
#0 0x55665e3dd463 <unknown>
#1 0x55665e1a18d8 <unknown>
#2 0x55665e1c9b6a <unknown>
#3 0x55665e1c4c05 <unknown>
#4 0x55665e208802 <unknown>
#5 0x55665e2082af <unknown>
#6 0x55665e200443 <unknown>
#7 0x55665e1d13c5 <unknown>
#8 0x55665e1d2531 <unknown>
#9 0x55665e42fdce <unknown>
#10 0x55665e433192 <unknown>
#11 0x55665e41493e <unknown>
#12 0x55665e434103 <unknown>
#13 0x55665e407d85 <unknown>
#14 0x55665e4550a8 <unknown>
#15 0x55665e455239 <unknown>
#16 0x55665e470492 <unknown>
#17 0x7f7cc2144609 start_thread

**What did you expect to happen?**
To at least get past the MFA stuff

**What actually happened?**
see stacktrace

**Additional context**

**Comment by sooth** [comment]
sigh getting the same shit again, this is getting tiring...

**Comment by gyllen** [comment]
It's a problem with selenium-requests that needs some "workaround", check this commit

**Comment by mrooney** [comment]
I wonder if we should pin a specific Chromedriver version to a specific Mint release and force downloading of that one so we know it is compatible with the version of selenium-requests that is being used? Is there a better solution?

**Comment by gyllen** [comment]
Kind of feels like selenium-requests should address this issue though, pinning a driver might just add other problems on different OSes.

**Comment by Crazee** [comment]
I'm back to using the docker version.  I trust @mrooney gets versions of all the pieces that get along together before pushing a new docker image...

**Comment by mrooney** [comment]
I don't personally use the docker version of this, so it would be great if someone is able to point to an existing PR (or create one) that pins the version or resolves this in a satisfactory manner, that I can review and merge + release. That would be a huge help, thanks!

**Comment by mrooney** [comment]
Thanks! I just released mintapi 2.12 which bumps the selenium-requests version to 2.0.3, which claims to future-proof their fix. That should address the issue, but let me know if not :)
