### ISSUE TITLE
invalid selector with selenium 4.8.3

### ISSUE THREAD

**Issue by dantidote** [mintapi/mintapi#598]
**Describe the bug**
It looks like there's a [behavior change](https://github.com/SeleniumHQ/selenium/issues/11842) in selenium 4.8.2+

We hit it because this selector is empty.  https://github.com/mintapi/mintapi/blob/251b10ec6492cf7049994893d6da9dfe7d66b25d/mintapi/signIn.py#L50

What version of MintAPI are you using? **latest / main**
What command[s] did you run / steps to reproduce?
Stacktrace/error received:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/mintapi/browser.py", line 119, in login_and_get_token
    self.status_message = sign_in(
  File "/usr/local/lib/python3.9/dist-packages/mintapi/signIn.py", line 396, in sign_in
    mfa_page(
  File "/usr/local/lib/python3.9/dist-packages/mintapi/signIn.py", line 620, in mfa_page
    mfa_result = search_mfa_method(driver)
  File "/usr/local/lib/python3.9/dist-packages/mintapi/signIn.py", line 667, in search_mfa_method
    span_text = driver.find_element(
  File "/usr/local/lib/python3.9/dist-packages/selenium/webdriver/remote/webdriver.py", line 830, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
  File "/usr/local/lib/python3.9/dist-packages/selenium/webdriver/remote/webdriver.py", line 440, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.9/dist-packages/selenium/webdriver/remote/errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidSelectorException: Message: invalid selector: No selector specified
  (Session info: headless chrome=108.0.5359.94)
```
**What did you expect to happen?**
No errors or continue past it.

**What actually happened?**
Script exits with stacktrace

**Additional context**
I guess we can catch `InvalidSelectorException` or maybe there's a better selector for this.

**Comment by anton-rusanov** [comment]
I am seeing the same error with selenium=4.8.1 and  chrome=114.0.5735.106. 

And Selenium folks in https://github.com/SeleniumHQ/selenium/issues/11842 say Chrome decides whether the selector is invalid. So it might be related to the Chrome version.

**Comment by nathan815** [comment]
This error is causing mintapi to not not work for me at all. It fails at the MFA login screen.

How is it working for everyone else?
