### ISSUE TITLE
NotImplementedError

### ISSUE THREAD

**Issue by pazwicker** [mintapi/mintapi#599]
**Describe the bug**

What version of MintAPI are you using?
2.14

What command[s] did you run / steps to reproduce?

```
mint = mintapi.Mint(
        mint_email,  # Email used to log in to Mint
        mint_password,  # Your password used to log in to mint
        mfa_method="soft-token",  # Can be 'sms' (default) or 'email'.
        headless=True,  # Whether the chromedriver should work without opening a
        mfa_input_callback=None,
        mfa_token=mint_mfa_token,
        session_path=None,
        wait_for_sync=False,  # do not wait for accounts to sync
        wait_for_sync_timeout=1,  # number of seconds to wait for sync
        use_rest_client=False
    )
```

Stacktrace/error received:

```
File "/Users/paz/Library/Python/3.9/lib/python/site-packages/mintapi/api.py", line 68, in __getattr__
    raise NotImplementedError
NotImplementedError
```

**What did you expect to happen?**

I expected the function to return the `mint` object

**What actually happened?**

The function errored before returning the object

**Additional context**

**Comment by vanillanesquik** [comment]
I am having this issue too when running mint.get_transactions(). Is there a solution to getting it running? Let me know if there is any information I can additionally provide. Thanks so much.

**Comment by CalvinChanCan** [comment]
I'm having trouble reproducing the error with the samples provided. @vanillanesquik , for your case, can you try:
`mint.get_transaction_data()` instead of `mint.get_transactions()`?

**Comment by vanillanesquik** [comment]
> I'm having trouble reproducing the error with the samples provided. @vanillanesquik , for your case, can you try: `mint.get_transaction_data()` instead of `mint.get_transactions()`?

Thanks - I got it figured out. I was using an outdated guide. Once I changed to "mint.get_transaction_data()" I still had a failure. I then needed to add "mint.get_account_data()" before getting the transactions it worked as expected.

**Comment by mrooney** [comment]
Thanks for the follow up @vanillanesquik ! What guide did you find that was outdated, is that something on our side that needs to be updated?

**Comment by bmiller08** [comment]
I have this same error recently. Specifically when calling `mint.get_bills()`:

```
Traceback (most recent call last):
  File "/home/ubuntu/Git/other/budget/create_budget.py", line 56, in <module>
    bills = mint.get_bills()
  File "/home/ubuntu/Git/other/budget/.venv/lib/python3.10/site-packages/mintapi/api.py", line 68, in __getattr__
    raise NotImplementedError
NotImplementedError
```

However I was able to get things to work by specifically reverting to version `2.10` and making sure `selenium-requests` was specifically using `2.0.3`. I tried a bunch of combinations of these things and decided to leave it alone once it worked. 

```
mintapi==2.10
selenium<=4.7.2
selenium-requests==2.0.3
```

**Comment by vanillanesquik** [comment]
> I have this same error recently. Specifically when calling `mint.get_bills()`:
> 
> ```
> Traceback (most recent call last):
>   File "/home/ubuntu/Git/other/budget/create_budget.py", line 56, in <module>
>     bills = mint.get_bills()
>   File "/home/ubuntu/Git/other/budget/.venv/lib/python3.10/site-packages/mintapi/api.py", line 68, in __getattr__
>     raise NotImplementedError
> NotImplementedError
> ```
> 
> However I was able to get things to work by specifically reverting to version `2.10` and making sure `selenium-requests` was specifically using `2.0.3`. I tried a bunch of combinations of these things and decided to leave it alone once it worked.
> 
> ```
> mintapi==2.10
> selenium<=4.7.2
> selenium-requests==2.0.3
> ```

Does the issue occur if you run: mint.get_transaction_data() before the mint.get_bills() ?

Thanks

**Comment by bmiller08** [comment]
> Does the issue occur if you run: mint.get_account_data() before the mint.get_bills() ?

Yes. Doesn't matter if that occurs before or after get_bills the result is the same.

**Comment by babbeuf** [comment]
> > Does the issue occur if you run: mint.get_account_data() before the mint.get_bills() ?
> 
> Yes. Doesn't matter if that occurs before or after get_bills the result is the same.

I am having the exact same issue, and reverting to 

`mintapi==2.10`
`selenium<=4.7.2`
`selenium-requests==2.0.3`

worked for me
