### ISSUE TITLE
Getting TypeError: __init__() got an unexpected keyword argument 'executable_path'` when running python example

### ISSUE THREAD

**Issue by dloza** [mintapi/mintapi#603]
`Traceback (most recent call last):
  File "/Users/dloza/mintupdater/tmp.py", line 3, in <module>
    mint = mintapi.Mint(
  File "/usr/local/lib/python3.9/site-packages/mintapi/api.py", line 33, in __init__
    self.browser = SeleniumBrowser(
  File "/usr/local/lib/python3.9/site-packages/mintapi/browser.py", line 57, in __init__
    self.login_and_get_token(
  File "/usr/local/lib/python3.9/site-packages/mintapi/browser.py", line 113, in login_and_get_token
    self.driver = driver or _create_web_driver_at_mint_com(
  File "/usr/local/lib/python3.9/site-packages/mintapi/signIn.py", line 313, in _create_web_driver_at_mint_com
    driver = Chrome(
  File "/usr/local/lib/python3.9/site-packages/seleniumrequests/request.py", line 148, in __init__
    super(RequestsSessionMixin, self).__init__(*args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'executable_path'`

**Comment by yongjunkim42** [comment]
Selenium 4.10 has this known issue(https://github.com/SeleniumHQ/selenium/issues/12180).  You can temporarily fix this issue by rolling Selenium to 4.9.

**Comment by basnijholt** [comment]
`pip install "selenium<4.10"`

**Comment by adrienhenneron** [comment]
I've got the same error and rolling Selenium to 4.9 doesn't fix the issue

**Comment by CalvinChanCan** [comment]
The issue seems to be that selenium fully depreciated `executable_path` in 4.10 (https://github.com/SeleniumHQ/selenium/issues/12176) but its still being used in here:

https://github.com/mintapi/mintapi/blob/main/mintapi/signIn.py#L315

**Comment by jprouty** [comment]
A better workaround is to use the `use_chromedriver_on_path` arg (or kwarg for cli). If you have a recent selenium version, this will use selenium manager under the hood and is way better/the right way to go by default going forward.

@basnijholt workaround stops working, as the Chromium/ChromeDriver team has changed how releases work, so the old way mintapi uses to download and use the latest version of ChromeDriver stopped working with Chrome release 114. (See `get_stable_chrome_driver`)

**Comment by jprouty** [comment]
My apologies (I was looking at the latest PyPI version); commit https://github.com/mintapi/mintapi/commit/6064dc1fdab77666b86ca4809e21538661f63499 fixes the issue. However this has yet to be released via PyPI / pip.
