### ISSUE TITLE
Mint Dashboard timeout

### ISSUE THREAD

**Issue by Gaurang-1402** [mintapi/mintapi#611]
Hi, 

I have been using a script to fetch my mint transactions. I last used the script in June. When I ran it recently, I faced many errors and could not see the webscraper go past the Mint dashboard. Here is the entire error:

```

DevTools listening on ws://127.0.0.1:62347/devtools/browser/a19d217c-b8a0-4045-b842-c73b3d2e69c9
[31376:14408:0821/154228.640:ERROR:socket_manager.cc(141)] Failed to resolve address for aa.online-metrix.net., errorcode: -105
[31376:14408:0821/154228.640:ERROR:socket_manager.cc(141)] Failed to resolve address for aa.online-metrix.net., errorcode: -105
[31376:14408:0821/154228.640:ERROR:socket_manager.cc(141)] Failed to resolve address for aa.online-metrix.net., errorcode: -105
[31376:14408:0821/154229.341:ERROR:socket_manager.cc(141)] Failed to resolve address for aa.online-metrix.net., errorcode: -105
[31376:14408:0821/154229.408:ERROR:socket_manager.cc(141)] Failed to resolve address for aa.online-metrix.net., errorcode: -105
[31376:14408:0821/154229.408:ERROR:socket_manager.cc(141)] Failed to resolve address for aa.online-metrix.net., errorcode: -105
[22776:31548:0821/154233.009:ERROR:device_event_log_impl.cc(222)] [15:42:33.008] USB: usb_service_win.cc:415 Could not read device interface GUIDs: The system cannot find the file specified. (0x2)
[22776:31548:0821/154233.010:ERROR:device_event_log_impl.cc(222)] [15:42:33.008] USB: usb_service_win.cc:104 SetupDiGetDeviceProperty({{A45C254E-DF1C-4EFD-8020-67D146A850E0}, 6}) failed: Element not found. (0x490)
Mint sync apparently incomplete after timeout.  Data retrieved may not be current.
start_date: 2023-06-18
end_date: 2023-08-13
Traceback (most recent call last):
  File "C:\Users\gaura\Desktop\Finances\Finance-code\mint_transactions.py", line 38, in <module>
    transactions = mint.get_transaction_data(DateFilter.Options(11), account_ids=[checking_account_id], start_date=start_date_str, end_date=end_date_str)
  File "C:\Users\gaura\AppData\Roaming\Python\Python39\site-packages\mintapi\endpoints.py", line 575, in get_transaction_data
    data = self._get_transaction_data(json=payload.to_dict(), **kwargs)
  File "C:\Users\gaura\AppData\Roaming\Python\Python39\site-packages\mintapi\endpoints.py", line 283, in _get_transaction_data
    return self.post(
  File "C:\Users\gaura\AppData\Roaming\Python\Python39\site-packages\mintapi\endpoints.py", line 37, in post
    return self.request(method="POST", **kwargs)
  File "C:\Users\gaura\AppData\Roaming\Python\Python39\site-packages\mintapi\browser.py", line 186, in request
    response = self.driver.request(
  File "C:\Users\gaura\AppData\Roaming\Python\Python39\site-packages\seleniumrequests\request.py", line 170, in request
    requested_tld = get_tld(url)
  File "C:\Users\gaura\AppData\Roaming\Python\Python39\site-packages\seleniumrequests\request.py", line 96, in get_tld
    components = tldextract.extract(url)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tldextract\tldextract.py", line 300, in extract
    return TLD_EXTRACTOR(url, include_psl_private_domains=include_psl_private_domains)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tldextract\tldextract.py", line 233, in __call__
    suffix_index = self._get_tld_extractor().suffix_index(
  File "C:\ProgramData\Anaconda3\lib\site-packages\tldextract\tldextract.py", line 274, in _get_tld_extractor
    public_tlds, private_tlds = get_suffix_lists(
  File "C:\ProgramData\Anaconda3\lib\site-packages\tldextract\suffix_list.py", line 55, in get_suffix_lists
    return cache.run_and_cache(
  File "C:\ProgramData\Anaconda3\lib\site-packages\tldextract\cache.py", line 188, in run_and_cache
    with FileLock(lock_path, timeout=self.lock_timeout):
  File "C:\Users\gaura\AppData\Roaming\Python\Python39\site-packages\filelock\_api.py", line 260, in __enter__
    self.acquire()
  File "C:\Users\gaura\AppData\Roaming\Python\Python39\site-packages\filelock\_api.py", line 226, in acquire
    raise Timeout(lock_filename)
filelock._error.Timeout: The file lock 'C:\ProgramData\Anaconda3\lib\site-packages\tldextract\.suffix_cache/publicsuffix.org-tlds\de84b5ca2167d4c83e38fb162f2e8738.tldextract.json.lock' could not be acquired.
```

The login worked perfectly but it always gets stuck on the Mint dashboard page. 

I recently upgraded my Mint Version to (although I faced that error before the upgrade also): 2.14
Selenium version: 4.9.0

**Comment by Gaurang-1402** [comment]
Hi, none of the APIs are working for me. I APIs other than get_transaction_data like get_networth but it always get stuck on

```
[22776:31548:0821/154233.010:ERROR:device_event_log_impl.cc(222)] [15:42:33.008] USB: usb_service_win.cc:104 SetupDiGetDeviceProperty({{A45C254E-DF1C-4EFD-8020-67D146A850E0}, 6}) failed: Element not found. (0x490)
```
