### ISSUE TITLE
get_bills() NotImplementedError

### ISSUE THREAD

**Issue by pazwicker** [mintapi/mintapi#619]
**Describe the bug**
When running `mint.get_bills()`, the script fails and raises the following error.

What version of MintAPI are you using?
`Version: 2.14`
Installed via `mintapi @ git+https://github.com/mintapi/mintapi.git`

What command[s] did you run / steps to reproduce?

Command: `mint.get_bills()`

Stacktrace/error received:

```
Traceback (most recent call last):
  File "/Users/paz/Documents/github/zwickfi/scripts/main.py", line 5, in <module>
    import mint_data
  File "/Users/paz/Documents/github/zwickfi/scripts/mint_data.py", line 129, in <module>
    mint_bills = mint_bills(mint)
  File "/Users/paz/Documents/github/zwickfi/scripts/mint_data.py", line 96, in mint_bills
    b = mint.get_bills()
  File "/Users/paz/Documents/github/zwickfi/venv/lib/python3.9/site-packages/mintapi/api.py", line 68, in __getattr__
    raise NotImplementedError
NotImplementedError
```

**What did you expect to happen?**

I expected mintapi to return bills from Mint.

**What actually happened?**

NotImplementedError :)

**Additional context**

Both of the following commands work fine
`mint.get_account_data()`

```
mint.get_transaction_data(
        date_filter="ALL_TIME",
        remove_pending=False,
    )
```

**Comment by CalvinChanCan** [comment]
For getting bills data, can you try:
```
mint.get_bills_data()
```

**Comment by pazwicker** [comment]
Hey @CalvinChanCan, running `mint.get_bills_data()` gives me this error:

```Traceback (most recent call last):
  File "/Users/paz/Documents/github/zwickfi/scripts/main.py", line 5, in <module>
    import mint_data
  File "/Users/paz/Documents/github/zwickfi/scripts/mint_data.py", line 129, in <module>
    mint_bills = mint_bills(mint)
  File "/Users/paz/Documents/github/zwickfi/scripts/mint_data.py", line 96, in mint_bills
    b = mint.get_bills_data()
  File "/Users/paz/Documents/github/zwickfi/venv/lib/python3.9/site-packages/mintapi/endpoints.py", line 380, in get_bills_data
    return self._get_bills_data(**kwargs)
  File "/Users/paz/Documents/github/zwickfi/venv/lib/python3.9/site-packages/mintapi/endpoints.py", line 171, in _get_bills_data
    return self.get(
  File "/Users/paz/Documents/github/zwickfi/venv/lib/python3.9/site-packages/mintapi/endpoints.py", line 34, in get
    return self.request(method="GET", **kwargs)
  File "/Users/paz/Documents/github/zwickfi/venv/lib/python3.9/site-packages/mintapi/browser.py", line 195, in request
    return self._paginate(
  File "/Users/paz/Documents/github/zwickfi/venv/lib/python3.9/site-packages/mintapi/endpoints.py", line 95, in _paginate
    response = self.request(
  File "/Users/paz/Documents/github/zwickfi/venv/lib/python3.9/site-packages/mintapi/browser.py", line 192, in request
    response.raise_for_status()
  File "/Users/paz/Documents/github/zwickfi/venv/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://mint.intuit.com/bps/v2/payer/bills?amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;offset=200&amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;limit=100&amp;amp;amp;offset=100&amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;limit=100&amp;amp;amp;amp;amp;amp;amp;amp;offset=100&amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;offset=100&amp;amp;offset=100&amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;limit=100&amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;limit=100&amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;limit=100&amp;amp;amp;limit=100&amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;limit=100&amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;limit=100&amp;amp;amp;amp;amp;amp;amp;amp;amp;limit=100&amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;offset=100&amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;limit=100&amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;offset=100&amp;amp;amp;amp;amp;amp;amp;offset=100&amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;offset=100&amp;amp;amp;amp;amp;offset=100&amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;offset=100&amp;amp;amp;amp;amp;amp;amp;amp;amp;offset=100&amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;offset=100&amp;amp;amp;amp;amp;amp;amp;limit=100&amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;limit=100&amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;offset=100&amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;offset=100&amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;offset=100&amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;limit=100&amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;limit=100&amp;amp;amp;amp;limit=100&amp;amp;amp;amp;amp;amp;offset=100&amp;amp;amp;amp;offset=100&amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;offset=100&amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;limit=100&amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;limit=100&amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;offset=100&amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;offset=100&amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;limit=100&amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;limit=100&amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;limit=100&amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;limit=100&amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;offset=100&amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;limit=100&amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;offset=100&amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;limit=100&amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;offset=100&amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;limit=100&amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;limit=100&amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;limit=100&amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;limit=100&amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;offset=100&amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;limit=100&amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;limit=100&amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;offset=100&amp;amp;amp;amp;amp;limit=100&amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;limit=100&amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;offset=100&amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;limit=100&amp;amp;amp;amp;amp;amp;amp;amp;limit=100&amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;offset=100&amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;limit=100&amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;offset=100&amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;limit=100&amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;offset=100&amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;limit=100&amp;amp;amp;amp;amp;amp;limit=100&amp;amp;limit=100&amp;offset=100&amp;limit=100
```

**Comment by CalvinChanCan** [comment]
@pazwicker can you provide how you're instantiating the mint object?

I can't seem to reproduce the error using the main branch using `get_bills_data`. For me, it seems to work as expected:


```
    client = Mint(
        email=email,
        password=password,
        mfa_method="soft-token",
        mfa_token=mfa_token,
        wait_for_sync=False,
        #use_rest_client=True,
    )

    res = client.get_bills_data()
    print(res)
```

**Comment by pazwicker** [comment]
@CalvinChanCan of course, see below.

```
def mint_connect():
    """Establish MintAPI connection using provided credentials."""
    return mintapi.Mint(
        mint_email,
        mint_password,
        mfa_method="soft-token",
        headless=True,
        mfa_input_callback=None,
        mfa_token=mint_mfa_token,
        session_path=None,
        wait_for_sync=False,
        wait_for_sync_timeout=1,
    )


# Connect to Mint.com
mint = mint_connect()


# Retrieve bills data
mint_bills = mint_bills_data(mint)

**Comment by CalvinChanCan** [comment]
Thanks. Can you share the function `mint_bills_data`?

I'm still unable to reproduce the issue. Though I've notice in your stacktrace, it seems like the `get_bills_data` seems to have been called successfully but what looks strange is the paginate function seems to have appended a bunch of `amp `s to the endpoint URL. I wonder if something is being passed as keyword args here?

https://github.com/mintapi/mintapi/blob/main/mintapi/endpoints.py#L100

```
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://mint.intuit.com/bps/v2/payer/bills?amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;offset=200&amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;limit=100&amp;amp;amp;o...
```

**Comment by pazwicker** [comment]
Hey @CalvinChanCan, sorry for missing that before! Here's that function:

```def mint_bills(mint):
    b = mint.get_bills_data() # previously mint.get_bills()
    df = pd.json_normalize(b)
    df.columns = df.columns.str.replace(" ", "_")
    df.columns = df.columns.str.replace(".", "_")
    df.columns = df.columns.str.lower()
    return df
```

**Comment by CalvinChanCan** [comment]
@pazwicker Sorry for the late reply.

For that section, I don't see anything that could be causing those appended `amp` to the url. One idea I had was can you try using `use_rest_client=True`?

**Comment by mrooney** [comment]
Have you tried 2.15? I believe there was a fix for this.
