### ISSUE TITLE
module 'mintapi' has no attribute 'DateFilter' using latest GitHub version

### ISSUE THREAD

**Issue by gabefortin** [mintapi/mintapi#620]
**Describe the bug**
Traceback (most recent call last):
  File "/home/gabe_fortin/PycharmProjects/budget_tracker/budget_updater_all_in_one.py", line 13, in <module>
    df = mint.get_transaction_data(date_filter=mintapi.DateFilter.Options.CUSTOM, start_date='01/01/23', end_date='12/31/23', limit=100000)
AttributeError: module 'mintapi' has no attribute 'DateFilter'

What version of MintAPI are you using?
It says 2.14 but I installed from GitHub latest this morning to get past the executable error.

What command[s] did you run / steps to reproduce?
mint.get_transaction_data(date_filter=mintapi.DateFilter.Options.CUSTOM, start_date='01/01/23', end_date='12/31/23', limit=100000)
Stacktrace/error received:
Traceback (most recent call last):
  File "/home/gabe_fortin/PycharmProjects/budget_tracker/budget_updater_all_in_one.py", line 13, in <module>
    df = mint.get_transaction_data(date_filter=mintapi.DateFilter.Options.CUSTOM, start_date='01/01/23', end_date='12/31/23', limit=100000)
AttributeError: module 'mintapi' has no attribute 'DateFilter'

**What did you expect to happen?**
Get transactions for 2023

**What actually happened?**
Error

**Additional context**
This worked fine until recently but I ran into a problem with PyPi version 2.14 of mintapi (executable...), upgraded mintapi direct from GitHub, that gets me past the executable problem but now says DateFilter attribute is gone...

**Comment by CalvinChanCan** [comment]
I'm unable to reproduce the error using the provided code.

Though try using this import which may help.
```
from mintapi.filters import DateFilter
```

**Comment by gabefortin** [comment]
Adding from mintapi.filters import DateFilter to api.py is allowing me to run some date filters, e.g.  I can use mint.get_transaction_data(date_filter=mintapi.DateFilter.Options.THIS_YEAR). For some reason the custom one with start and end dates doesn't work. Have not really had time to dig it... but good enough for now.
